type Difficulty = 'Beginner' | 'Intermediate' | 'Advanced';

type SchemaColumn = {
  name: string;
  type: string;
  constraint: string;
};

type SampleTable = {
  name: string;
  rowCount: string;
  headers: string[];
  rows: (string | number)[][];
};

const schemaFrom = (rows: Array<[string, string, string]>): SchemaColumn[] =>
  rows.map(([name, type, description]) => ({
    name,
    type,
    constraint: description,
  }));

const table = (
  name: string,
  headers: string[],
  rows: (string | number)[][],
  rowCount = `${rows.length} rows`
): SampleTable => ({ name, rowCount, headers, rows });

export const pythonDrills = {
  'python-drill-1': {
    id: 'python-drill-1',
    number: 1,
    title: 'Retail Sales Revenue Analysis',
    tool: 'Python' as const,
    difficulty: 'Beginner' as Difficulty,
    skills: ['Pandas', 'DataFrame', 'GroupBy', 'Aggregation', 'SUM'],
    description: 'Find the total revenue generated by each product category using Python and Pandas.',
    setup: 'Your dataset contains a sales_data DataFrame with order-level retail sales information, including product category, quantity, unit price, and order date.',
    schema: {
      sales_data: schemaFrom([
        ['order_id', 'INT', 'Unique order ID'],
        ['product_category', 'VARCHAR(50)', 'Product category name'],
        ['quantity', 'INT', 'Number of units sold'],
        ['unit_price', 'FLOAT', 'Price per unit'],
        ['order_date', 'DATE', 'Date of order'],
      ]),
    },
    sampleTables: [
      table('sales_data', ['order_id', 'product_category', 'quantity', 'unit_price', 'order_date'], [
        [101, 'Electronics', 2, 15000, '2023-07-01'],
        [102, 'Clothing', 5, 1200, '2023-07-02'],
        [103, 'Electronics', 1, 25000, '2023-07-03'],
        [104, 'Grocery', 10, 300, '2023-07-04'],
        [105, 'Clothing', 3, 1500, '2023-07-05'],
        [106, 'Grocery', 8, 250, '2023-07-06'],
        [107, 'Furniture', 1, 18000, '2023-07-07'],
        [108, 'Electronics', 3, 10000, '2023-07-08'],
      ]),
    ],
    departmentData: [] as { id: number; name: string }[],
    employeeData: [] as { id: number; name: string; salary: string; joining_date: string; department_id: number }[],
    task: 'Revenue Analysis: What is the total revenue generated by each product category?\n\nYour result table should have product_category and total_revenue columns.',
    outputColumns: ['product_category', 'total_revenue'],
    expectedOutputPreview: [
      { product_category: 'Electronics', total_revenue: '85000' },
      { product_category: 'Furniture', total_revenue: '18000' },
      { product_category: '...', total_revenue: '...' },
    ] as Record<string, string>[],
    hint: undefined as string[] | undefined,
    hintTitle: undefined as string | undefined,
    solution: {
      sql: `# Retail Sales Revenue Analysis
import pandas as pd

sales_data = pd.DataFrame({
    "order_id": [101, 102, 103, 104, 105, 106, 107, 108],
    "product_category": ["Electronics", "Clothing", "Electronics", "Grocery", "Clothing", "Grocery", "Furniture", "Electronics"],
    "quantity": [2, 5, 1, 10, 3, 8, 1, 3],
    "unit_price": [15000, 1200, 25000, 300, 1500, 250, 18000, 10000],
    "order_date": ["2023-07-01", "2023-07-02", "2023-07-03", "2023-07-04", "2023-07-05", "2023-07-06", "2023-07-07", "2023-07-08"],
})

sales_data["revenue"] = sales_data["quantity"] * sales_data["unit_price"]

result = (
    sales_data
    .groupby("product_category", as_index=False)["revenue"]
    .sum()
    .rename(columns={"revenue": "total_revenue"})
    .sort_values(by="total_revenue", ascending=False)
)

print(result)`,
      howItWorks: [
        'Create a revenue column by multiplying quantity with unit_price.',
        'Group rows by product_category to calculate category-wise revenue.',
        'Use sum() to add revenue within each category.',
        'Rename the aggregated column to total_revenue and sort highest to lowest.',
      ],
      commonMistake: undefined as { title: string; points: string[] } | undefined,
      observation: undefined as { title: string; points: string[] } | undefined,
      result: [
        { product_category: 'Electronics', total_revenue: '85000' },
        { product_category: 'Furniture', total_revenue: '18000' },
        { product_category: 'Clothing', total_revenue: '10500' },
        { product_category: 'Grocery', total_revenue: '5000' },
      ] as Record<string, string>[],
    },
  },
  'python-drill-2': {
    id: 'python-drill-2',
    number: 2,
    title: 'Employee Performance Analysis',
    tool: 'Python' as const,
    difficulty: 'Beginner' as Difficulty,
    skills: ['Pandas', 'GroupBy', 'Aggregation', 'Mean', 'SUM'],
    description: 'Find the average performance score and total projects completed by each department using Python and Pandas.',
    setup: 'Your dataset contains an employee_performance DataFrame with employee, department, completed projects, and performance score data.',
    schema: {
      employee_performance: schemaFrom([
        ['employee_id', 'INT', 'Unique employee ID'],
        ['employee_name', 'VARCHAR(50)', 'Employee name'],
        ['department', 'VARCHAR(50)', 'Department name'],
        ['projects_completed', 'INT', 'Number of completed projects'],
        ['performance_score', 'FLOAT', 'Employee performance score'],
      ]),
    },
    sampleTables: [
      table('employee_performance', ['employee_id', 'employee_name', 'department', 'projects_completed', 'performance_score'], [
        [101, 'Alice', 'HR', 8, 82],
        [102, 'Bob', 'IT', 12, 91],
        [103, 'Charlie', 'HR', 6, 76],
        [104, 'David', 'Finance', 10, 88],
        [105, 'Eva', 'IT', 15, 95],
        [106, 'Frank', 'Finance', 7, 81],
        [107, 'Grace', 'IT', 11, 89],
        [108, 'Henry', 'HR', 9, 84],
      ]),
    ],
    departmentData: [] as { id: number; name: string }[],
    employeeData: [] as { id: number; name: string; salary: string; joining_date: string; department_id: number }[],
    task: 'Performance Analysis: What is the average performance score and total projects completed by each department?',
    outputColumns: ['department', 'average_performance_score', 'total_projects_completed'],
    expectedOutputPreview: [
      { department: 'Finance', average_performance_score: '84.50', total_projects_completed: '17' },
      { department: 'HR', average_performance_score: '80.67', total_projects_completed: '23' },
      { department: '...', average_performance_score: '...', total_projects_completed: '...' },
    ] as Record<string, string>[],
    hint: undefined as string[] | undefined,
    hintTitle: undefined as string | undefined,
    solution: {
      sql: `# Employee Performance Analysis
import pandas as pd

employee_performance = pd.DataFrame({
    "employee_id": [101, 102, 103, 104, 105, 106, 107, 108],
    "employee_name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace", "Henry"],
    "department": ["HR", "IT", "HR", "Finance", "IT", "Finance", "IT", "HR"],
    "projects_completed": [8, 12, 6, 10, 15, 7, 11, 9],
    "performance_score": [82, 91, 76, 88, 95, 81, 89, 84],
})

result = (
    employee_performance
    .groupby("department", as_index=False)
    .agg(
        average_performance_score=("performance_score", "mean"),
        total_projects_completed=("projects_completed", "sum"),
    )
)

result["average_performance_score"] = result["average_performance_score"].round(2)
print(result)`,
      howItWorks: [
        'Group employees department-wise with groupby("department").',
        'Use mean() to calculate average performance score.',
        'Use sum() to calculate total projects completed.',
        'Round the average score to two decimals for reporting.',
      ],
      commonMistake: undefined as { title: string; points: string[] } | undefined,
      observation: undefined as { title: string; points: string[] } | undefined,
      result: [
        { department: 'Finance', average_performance_score: '84.50', total_projects_completed: '17' },
        { department: 'HR', average_performance_score: '80.67', total_projects_completed: '23' },
        { department: 'IT', average_performance_score: '91.67', total_projects_completed: '38' },
      ] as Record<string, string>[],
    },
  },
  'python-drill-3': {
    id: 'python-drill-3',
    number: 3,
    title: 'Student Performance & Scholarship Analysis',
    tool: 'Python' as const,
    difficulty: 'Intermediate' as Difficulty,
    skills: ['Pandas', 'NumPy', 'If-Else', 'Lambda', 'Apply', 'Ranking'],
    description: 'Analyze student performance, grade category, scholarship eligibility, weakest subject, and class ranking.',
    setup: 'Your dataset contains a student_marks DataFrame with marks in three subjects and attendance percentage.',
    schema: {
      student_marks: schemaFrom([
        ['student_id', 'INT', 'Unique student ID'],
        ['student_name', 'VARCHAR(50)', 'Student name'],
        ['class_section', 'VARCHAR(10)', 'Student class section'],
        ['maths', 'INT', 'Marks scored in Maths'],
        ['science', 'INT', 'Marks scored in Science'],
        ['english', 'INT', 'Marks scored in English'],
        ['attendance_pct', 'FLOAT', 'Student attendance percentage'],
      ]),
    },
    sampleTables: [
      table('student_marks', ['student_id', 'student_name', 'class_section', 'maths', 'science', 'english', 'attendance_pct'], [
        [101, 'Aarav', 'A', 85, 78, 90, 92],
        [102, 'Meera', 'A', 72, 68, 75, 88],
        [103, 'Rohan', 'B', 45, 52, 48, 76],
        [104, 'Priya', 'A', 91, 88, 94, 95],
        [105, 'Kabir', 'B', 60, 65, 58, 81],
        [106, 'Ananya', 'B', 33, 40, 38, 69],
        [107, 'Dev', 'A', 76, 81, 79, 84],
        [108, 'Isha', 'B', 95, 92, 89, 97],
      ]),
    ],
    departmentData: [] as { id: number; name: string }[],
    employeeData: [] as { id: number; name: string; salary: string; joining_date: string; department_id: number }[],
    task: 'Calculate total marks and average marks for each student.\nAssign grade using average marks.\nIdentify scholarship eligibility using marks and attendance.\nFind the weakest subject for each student.\nRank students based on average marks.',
    outputColumns: ['student_id', 'student_name', 'total_marks', 'average_marks', 'grade', 'scholarship_status', 'weakest_subject', 'performance_rank'],
    expectedOutputPreview: [
      { student_id: '108', student_name: 'Isha', total_marks: '276', average_marks: '92.00', grade: 'A', scholarship_status: 'Eligible', weakest_subject: 'english', performance_rank: '1' },
      { student_id: '104', student_name: 'Priya', total_marks: '273', average_marks: '91.00', grade: 'A', scholarship_status: 'Eligible', weakest_subject: 'science', performance_rank: '2' },
      { student_id: '...', student_name: '...', total_marks: '...', average_marks: '...', grade: '...', scholarship_status: '...', weakest_subject: '...', performance_rank: '...' },
    ] as Record<string, string>[],
    hint: ['Use sum(axis=1) and mean(axis=1) for row-wise marks calculations.', 'Use np.select for grade assignment and rank(method="dense") for ranking.'],
    hintTitle: 'Python Hint',
    solution: {
      sql: `# Student Performance & Scholarship Analysis
import pandas as pd
import numpy as np

student_marks = pd.DataFrame({
    "student_id": [101, 102, 103, 104, 105, 106, 107, 108],
    "student_name": ["Aarav", "Meera", "Rohan", "Priya", "Kabir", "Ananya", "Dev", "Isha"],
    "class_section": ["A", "A", "B", "A", "B", "B", "A", "B"],
    "maths": [85, 72, 45, 91, 60, 33, 76, 95],
    "science": [78, 68, 52, 88, 65, 40, 81, 92],
    "english": [90, 75, 48, 94, 58, 38, 79, 89],
    "attendance_pct": [92, 88, 76, 95, 81, 69, 84, 97],
})

student_marks["total_marks"] = student_marks[["maths", "science", "english"]].sum(axis=1)
student_marks["average_marks"] = student_marks[["maths", "science", "english"]].mean(axis=1).round(2)

conditions = [student_marks["average_marks"] >= 85, student_marks["average_marks"] >= 70, student_marks["average_marks"] >= 50]
student_marks["grade"] = np.select(conditions, ["A", "B", "C"], default="Fail")

student_marks["scholarship_status"] = student_marks.apply(
    lambda x: "Eligible" if x["average_marks"] >= 85 and x["attendance_pct"] >= 90 else "Not Eligible",
    axis=1,
)
student_marks["weakest_subject"] = student_marks[["maths", "science", "english"]].idxmin(axis=1)
student_marks["performance_rank"] = student_marks["average_marks"].rank(method="dense", ascending=False).astype(int)

result = student_marks[[
    "student_id", "student_name", "class_section", "total_marks", "average_marks",
    "grade", "attendance_pct", "scholarship_status", "weakest_subject", "performance_rank"
]].sort_values("performance_rank")

print(result)`,
      howItWorks: [
        'Row-wise sum and mean calculate total and average marks.',
        'np.select applies grade bands in priority order.',
        'apply with lambda checks scholarship eligibility using marks and attendance.',
        'idxmin identifies the subject with the lowest mark for each student.',
        'Dense ranking assigns continuous rank values from highest average marks to lowest.',
      ],
      commonMistake: undefined as { title: string; points: string[] } | undefined,
      observation: undefined as { title: string; points: string[] } | undefined,
      result: [
        { student_id: '108', student_name: 'Isha', total_marks: '276', average_marks: '92.00', grade: 'A', scholarship_status: 'Eligible', weakest_subject: 'english', performance_rank: '1' },
        { student_id: '104', student_name: 'Priya', total_marks: '273', average_marks: '91.00', grade: 'A', scholarship_status: 'Eligible', weakest_subject: 'science', performance_rank: '2' },
        { student_id: '101', student_name: 'Aarav', total_marks: '253', average_marks: '84.33', grade: 'B', scholarship_status: 'Not Eligible', weakest_subject: 'science', performance_rank: '3' },
        { student_id: '107', student_name: 'Dev', total_marks: '236', average_marks: '78.67', grade: 'B', scholarship_status: 'Not Eligible', weakest_subject: 'maths', performance_rank: '4' },
        { student_id: '102', student_name: 'Meera', total_marks: '215', average_marks: '71.67', grade: 'B', scholarship_status: 'Not Eligible', weakest_subject: 'science', performance_rank: '5' },
        { student_id: '105', student_name: 'Kabir', total_marks: '183', average_marks: '61.00', grade: 'C', scholarship_status: 'Not Eligible', weakest_subject: 'english', performance_rank: '6' },
        { student_id: '103', student_name: 'Rohan', total_marks: '145', average_marks: '48.33', grade: 'Fail', scholarship_status: 'Not Eligible', weakest_subject: 'maths', performance_rank: '7' },
        { student_id: '106', student_name: 'Ananya', total_marks: '111', average_marks: '37.00', grade: 'Fail', scholarship_status: 'Not Eligible', weakest_subject: 'maths', performance_rank: '8' },
      ] as Record<string, string>[],
    },
  },
  'python-drill-4': {
    id: 'python-drill-4',
    number: 4,
    title: 'Customer Profitability & Loyalty Analysis',
    tool: 'Python' as const,
    difficulty: 'Intermediate' as Difficulty,
    skills: ['Pandas', 'NumPy', 'GroupBy', 'Segmentation', 'Ranking'],
    description: 'Analyze customer profitability, loyalty, spending behavior, profit margin, and high-value customer status.',
    setup: 'Your dataset contains customer_orders with repeated customer orders, order amounts, city, and profit values.',
    schema: {
      customer_orders: schemaFrom([
        ['customer_id', 'INT', 'Unique customer ID'],
        ['customer_name', 'VARCHAR(50)', 'Customer name'],
        ['city', 'VARCHAR(50)', 'Customer city'],
        ['order_amount', 'FLOAT', 'Order amount'],
        ['profit', 'FLOAT', 'Profit earned from the order'],
      ]),
    },
    sampleTables: [
      table('customer_orders', ['customer_id', 'customer_name', 'city', 'order_amount', 'profit'], [
        [101, 'Rahul', 'Mumbai', 15000, 2500],
        [102, 'Priya', 'Delhi', 12000, 1800],
        [101, 'Rahul', 'Mumbai', 18000, 3200],
        [103, 'Aman', 'Kolkata', 8000, 900],
        [104, 'Sneha', 'Bangalore', 25000, 4200],
        [102, 'Priya', 'Delhi', 14000, 2200],
        [105, 'Vikram', 'Pune', 30000, 5500],
        [101, 'Rahul', 'Mumbai', 22000, 4100],
        [103, 'Aman', 'Kolkata', 11000, 1300],
        [105, 'Vikram', 'Pune', 27000, 4800],
      ]),
    ],
    departmentData: [] as { id: number; name: string }[],
    employeeData: [] as { id: number; name: string; salary: string; joining_date: string; department_id: number }[],
    task: 'Calculate total sales, total profit, average order value, and total orders for each customer.\nAssign customer segments using sales thresholds.\nCalculate profit margin percentage.\nRank customers based on total profit.\nIdentify high-value customers where profit margin is above 15% and total orders are at least 2.',
    outputColumns: ['customer_id', 'customer_name', 'total_sales', 'total_profit', 'total_orders', 'customer_segment', 'profit_rank', 'high_value_customer'],
    expectedOutputPreview: [
      { customer_id: '105', customer_name: 'Vikram', total_sales: '57000', total_profit: '10300', total_orders: '2', customer_segment: 'Platinum', profit_rank: '1', high_value_customer: 'Yes' },
      { customer_id: '101', customer_name: 'Rahul', total_sales: '55000', total_profit: '9800', total_orders: '3', customer_segment: 'Platinum', profit_rank: '2', high_value_customer: 'Yes' },
      { customer_id: '...', customer_name: '...', total_sales: '...', total_profit: '...', total_orders: '...', customer_segment: '...', profit_rank: '...', high_value_customer: '...' },
    ] as Record<string, string>[],
    hint: ['Aggregate at customer level before applying segment, margin, and rank logic.'],
    hintTitle: 'Python Hint',
    solution: {
      sql: `# Customer Profitability & Loyalty Analysis
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "customer_id": [101, 102, 101, 103, 104, 102, 105, 101, 103, 105],
    "customer_name": ["Rahul", "Priya", "Rahul", "Aman", "Sneha", "Priya", "Vikram", "Rahul", "Aman", "Vikram"],
    "city": ["Mumbai", "Delhi", "Mumbai", "Kolkata", "Bangalore", "Delhi", "Pune", "Mumbai", "Kolkata", "Pune"],
    "order_amount": [15000, 12000, 18000, 8000, 25000, 14000, 30000, 22000, 11000, 27000],
    "profit": [2500, 1800, 3200, 900, 4200, 2200, 5500, 4100, 1300, 4800],
})

summary = (
    df.groupby(["customer_id", "customer_name"])
    .agg(
        total_sales=("order_amount", "sum"),
        total_profit=("profit", "sum"),
        average_order_value=("order_amount", "mean"),
        total_orders=("order_amount", "count"),
    )
    .reset_index()
)

summary["profit_margin_pct"] = (summary["total_profit"] / summary["total_sales"] * 100).round(2)
summary["customer_segment"] = np.select(
    [summary["total_sales"] >= 50000, summary["total_sales"] >= 30000, summary["total_sales"] >= 15000],
    ["Platinum", "Gold", "Silver"],
    default="Bronze",
)
summary["profit_rank"] = summary["total_profit"].rank(method="dense", ascending=False).astype(int)
summary["high_value_customer"] = summary.apply(
    lambda x: "Yes" if x["profit_margin_pct"] > 15 and x["total_orders"] >= 2 else "No",
    axis=1,
)

print(summary.sort_values("profit_rank"))`,
      howItWorks: [
        'GroupBy creates one row per customer.',
        'Multiple aggregations calculate sales, profit, order value, and order frequency.',
        'np.select assigns business segments from sales thresholds.',
        'Profit rank is based on total profit in descending order.',
        'A lambda flags high-value customers using margin and order frequency.',
      ],
      commonMistake: undefined as { title: string; points: string[] } | undefined,
      observation: undefined as { title: string; points: string[] } | undefined,
      result: [
        { customer_id: '105', customer_name: 'Vikram', total_sales: '57000', total_profit: '10300', total_orders: '2', customer_segment: 'Platinum', profit_rank: '1', high_value_customer: 'Yes' },
        { customer_id: '101', customer_name: 'Rahul', total_sales: '55000', total_profit: '9800', total_orders: '3', customer_segment: 'Platinum', profit_rank: '2', high_value_customer: 'Yes' },
        { customer_id: '104', customer_name: 'Sneha', total_sales: '25000', total_profit: '4200', total_orders: '1', customer_segment: 'Silver', profit_rank: '3', high_value_customer: 'No' },
        { customer_id: '102', customer_name: 'Priya', total_sales: '26000', total_profit: '4000', total_orders: '2', customer_segment: 'Silver', profit_rank: '4', high_value_customer: 'Yes' },
        { customer_id: '103', customer_name: 'Aman', total_sales: '19000', total_profit: '2200', total_orders: '2', customer_segment: 'Silver', profit_rank: '5', high_value_customer: 'No' },
      ] as Record<string, string>[],
    },
  },
  'python-drill-5': {
    id: 'python-drill-5',
    number: 5,
    title: 'Bank Loan Risk Analysis',
    tool: 'Python' as const,
    difficulty: 'Intermediate' as Difficulty,
    skills: ['Pandas', 'NumPy', 'Risk Analysis', 'Lambda', 'GroupBy'],
    description: 'Analyze loan applicants and classify financial risk, loan eligibility, and income-group summary metrics.',
    setup: 'Your dataset contains loan_applications with applicant income, loan amount, credit score, and existing EMI.',
    schema: {
      loan_applications: schemaFrom([
        ['applicant_id', 'INT', 'Unique applicant ID'],
        ['applicant_name', 'VARCHAR(50)', 'Applicant name'],
        ['age', 'INT', 'Applicant age'],
        ['monthly_income', 'FLOAT', 'Monthly income of applicant'],
        ['loan_amount', 'FLOAT', 'Requested loan amount'],
        ['credit_score', 'INT', 'Applicant credit score'],
        ['existing_emi', 'FLOAT', 'Existing monthly EMI amount'],
      ]),
    },
    sampleTables: [
      table('loan_applications', ['applicant_id', 'applicant_name', 'age', 'monthly_income', 'loan_amount', 'credit_score', 'existing_emi'], [
        [201, 'Ramesh', 32, 65000, 800000, 760, 12000],
        [202, 'Sneha', 28, 48000, 600000, 690, 9000],
        [203, 'Arjun', 41, 90000, 1500000, 810, 25000],
        [204, 'Nisha', 35, 55000, 700000, 620, 18000],
        [205, 'Karan', 45, 120000, 2000000, 780, 30000],
        [206, 'Pooja', 26, 38000, 500000, 640, 7000],
        [207, 'Manav', 39, 75000, 950000, 710, 16000],
        [208, 'Riya', 31, 52000, 400000, 730, 8000],
      ]),
    ],
    departmentData: [] as { id: number; name: string }[],
    employeeData: [] as { id: number; name: string; salary: string; joining_date: string; department_id: number }[],
    task: 'Calculate EMI-to-income percentage and loan-to-income ratio.\nAssign risk category using credit score and EMI burden.\nIdentify whether the applicant is loan eligible.\nCreate income groups and summarize average loan amount by income group.',
    outputColumns: ['applicant_id', 'applicant_name', 'emi_to_income_pct', 'loan_to_income_ratio', 'risk_category', 'loan_eligibility', 'income_group'],
    expectedOutputPreview: [
      { applicant_id: '201', applicant_name: 'Ramesh', emi_to_income_pct: '18.46', loan_to_income_ratio: '1.03', risk_category: 'Low Risk', loan_eligibility: 'Eligible', income_group: 'Middle Income' },
      { applicant_id: '202', applicant_name: 'Sneha', emi_to_income_pct: '18.75', loan_to_income_ratio: '1.04', risk_category: 'Medium Risk', loan_eligibility: 'Eligible', income_group: 'Low Income' },
      { applicant_id: '...', applicant_name: '...', emi_to_income_pct: '...', loan_to_income_ratio: '...', risk_category: '...', loan_eligibility: '...', income_group: '...' },
    ] as Record<string, string>[],
    hint: ['Use np.select for risk categories, then a custom function for income_group.'],
    hintTitle: 'Python Hint',
    solution: {
      sql: `# Bank Loan Risk Analysis
import pandas as pd
import numpy as np

loan_applications = pd.DataFrame({
    "applicant_id": [201, 202, 203, 204, 205, 206, 207, 208],
    "applicant_name": ["Ramesh", "Sneha", "Arjun", "Nisha", "Karan", "Pooja", "Manav", "Riya"],
    "age": [32, 28, 41, 35, 45, 26, 39, 31],
    "monthly_income": [65000, 48000, 90000, 55000, 120000, 38000, 75000, 52000],
    "loan_amount": [800000, 600000, 1500000, 700000, 2000000, 500000, 950000, 400000],
    "credit_score": [760, 690, 810, 620, 780, 640, 710, 730],
    "existing_emi": [12000, 9000, 25000, 18000, 30000, 7000, 16000, 8000],
})

loan_applications["emi_to_income_pct"] = (loan_applications["existing_emi"] / loan_applications["monthly_income"] * 100).round(2)
loan_applications["loan_to_income_ratio"] = (loan_applications["loan_amount"] / (loan_applications["monthly_income"] * 12)).round(2)

loan_applications["risk_category"] = np.select(
    [
        (loan_applications["credit_score"] >= 750) & (loan_applications["emi_to_income_pct"] <= 30),
        (loan_applications["credit_score"] >= 680) & (loan_applications["emi_to_income_pct"] <= 40),
        loan_applications["credit_score"] >= 620,
    ],
    ["Low Risk", "Medium Risk", "High Risk"],
    default="Very High Risk",
)
loan_applications["loan_eligibility"] = loan_applications.apply(
    lambda x: "Eligible" if x["credit_score"] >= 680 and x["emi_to_income_pct"] <= 35 else "Not Eligible",
    axis=1,
)

def income_group(income):
    if income >= 100000:
        return "High Income"
    if income >= 60000:
        return "Middle Income"
    return "Low Income"

loan_applications["income_group"] = loan_applications["monthly_income"].apply(income_group)

income_summary = loan_applications.groupby("income_group", as_index=False).agg(
    average_loan_amount=("loan_amount", "mean"),
    average_credit_score=("credit_score", "mean"),
    applicant_count=("applicant_id", "count"),
)

print(loan_applications[[
    "applicant_id", "applicant_name", "emi_to_income_pct", "loan_to_income_ratio",
    "risk_category", "loan_eligibility", "income_group"
]])
print(income_summary.round(2))`,
      howItWorks: [
        'EMI burden and loan-to-income ratio convert raw financial data into risk signals.',
        'np.select applies credit-score and EMI rules in order.',
        'A lambda checks eligibility from credit score and EMI-to-income percentage.',
        'A custom function creates readable income groups.',
        'GroupBy summarizes loan and credit metrics by income group.',
      ],
      commonMistake: undefined as { title: string; points: string[] } | undefined,
      observation: undefined as { title: string; points: string[] } | undefined,
      result: [
        { applicant_id: '201', applicant_name: 'Ramesh', emi_to_income_pct: '18.46', loan_to_income_ratio: '1.03', risk_category: 'Low Risk', loan_eligibility: 'Eligible', income_group: 'Middle Income' },
        { applicant_id: '202', applicant_name: 'Sneha', emi_to_income_pct: '18.75', loan_to_income_ratio: '1.04', risk_category: 'Medium Risk', loan_eligibility: 'Eligible', income_group: 'Low Income' },
        { applicant_id: '203', applicant_name: 'Arjun', emi_to_income_pct: '27.78', loan_to_income_ratio: '1.39', risk_category: 'Low Risk', loan_eligibility: 'Eligible', income_group: 'Middle Income' },
        { applicant_id: '204', applicant_name: 'Nisha', emi_to_income_pct: '32.73', loan_to_income_ratio: '1.06', risk_category: 'High Risk', loan_eligibility: 'Not Eligible', income_group: 'Low Income' },
        { applicant_id: '205', applicant_name: 'Karan', emi_to_income_pct: '25.00', loan_to_income_ratio: '1.39', risk_category: 'Low Risk', loan_eligibility: 'Eligible', income_group: 'High Income' },
        { applicant_id: '206', applicant_name: 'Pooja', emi_to_income_pct: '18.42', loan_to_income_ratio: '1.10', risk_category: 'High Risk', loan_eligibility: 'Not Eligible', income_group: 'Low Income' },
        { applicant_id: '207', applicant_name: 'Manav', emi_to_income_pct: '21.33', loan_to_income_ratio: '1.06', risk_category: 'Medium Risk', loan_eligibility: 'Eligible', income_group: 'Middle Income' },
        { applicant_id: '208', applicant_name: 'Riya', emi_to_income_pct: '15.38', loan_to_income_ratio: '0.64', risk_category: 'Medium Risk', loan_eligibility: 'Eligible', income_group: 'Low Income' },
      ] as Record<string, string>[],
    },
  },
  'python-drill-6': {
    id: 'python-drill-6',
    number: 6,
    title: 'Hospital Patient Visit Analysis',
    tool: 'Python' as const,
    difficulty: 'Intermediate' as Difficulty,
    skills: ['Pandas', 'NumPy', 'Healthcare Analytics', 'Lambda', 'GroupBy'],
    description: 'Analyze patient visits, treatment costs, insurance discounts, age risk, and department-wise revenue.',
    setup: 'Your dataset contains patient_visits with visit type, department, consultation fee, medicine cost, and insurance status.',
    schema: {
      patient_visits: schemaFrom([
        ['patient_id', 'INT', 'Unique patient ID'],
        ['patient_name', 'VARCHAR(50)', 'Patient name'],
        ['age', 'INT', 'Patient age'],
        ['department', 'VARCHAR(50)', 'Hospital department visited'],
        ['visit_type', 'VARCHAR(30)', 'Type of visit'],
        ['consultation_fee', 'FLOAT', 'Consultation fee charged'],
        ['medicine_cost', 'FLOAT', 'Medicine cost charged'],
        ['insurance_covered', 'VARCHAR(10)', 'Whether insurance is available'],
      ]),
    },
    sampleTables: [
      table('patient_visits', ['patient_id', 'patient_name', 'age', 'department', 'visit_type', 'consultation_fee', 'medicine_cost', 'insurance_covered'], [
        [301, 'Amit', 45, 'Cardiology', 'Follow-up', 1200, 3500, 'Yes'],
        [302, 'Neha', 29, 'Dermatology', 'New', 800, 1200, 'No'],
        [303, 'Suresh', 63, 'Orthopedics', 'New', 1500, 4200, 'Yes'],
        [304, 'Kavita', 52, 'Cardiology', 'Emergency', 2500, 8500, 'Yes'],
        [305, 'Imran', 34, 'Neurology', 'New', 2000, 5000, 'No'],
        [306, 'Ritu', 41, 'Dermatology', 'Follow-up', 800, 900, 'Yes'],
        [307, 'Joseph', 70, 'Orthopedics', 'Emergency', 3000, 9500, 'Yes'],
        [308, 'Meenal', 26, 'Neurology', 'Follow-up', 1800, 2500, 'No'],
      ]),
    ],
    departmentData: [] as { id: number; name: string }[],
    employeeData: [] as { id: number; name: string; salary: string; joining_date: string; department_id: number }[],
    task: 'Calculate total treatment cost for each patient.\nApply a 20% insurance discount for insured patients.\nClassify age risk as Senior, Adult, or Young.\nIdentify high-cost patients where final bill is above 8000.\nSummarize total revenue and patient count by department.',
    outputColumns: ['patient_id', 'patient_name', 'department', 'total_treatment_cost', 'final_bill', 'age_risk_group', 'high_cost_patient'],
    expectedOutputPreview: [
      { patient_id: '301', patient_name: 'Amit', department: 'Cardiology', total_treatment_cost: '4700', final_bill: '3760.0', age_risk_group: 'Adult', high_cost_patient: 'No' },
      { patient_id: '302', patient_name: 'Neha', department: 'Dermatology', total_treatment_cost: '2000', final_bill: '2000.0', age_risk_group: 'Young', high_cost_patient: 'No' },
      { patient_id: '...', patient_name: '...', department: '...', total_treatment_cost: '...', final_bill: '...', age_risk_group: '...', high_cost_patient: '...' },
    ] as Record<string, string>[],
    hint: ['final_bill depends on insurance_covered, so apply row-wise logic before department aggregation.'],
    hintTitle: 'Python Hint',
    solution: {
      sql: `# Hospital Patient Visit Analysis
import pandas as pd
import numpy as np

patient_visits = pd.DataFrame({
    "patient_id": [301, 302, 303, 304, 305, 306, 307, 308],
    "patient_name": ["Amit", "Neha", "Suresh", "Kavita", "Imran", "Ritu", "Joseph", "Meenal"],
    "age": [45, 29, 63, 52, 34, 41, 70, 26],
    "department": ["Cardiology", "Dermatology", "Orthopedics", "Cardiology", "Neurology", "Dermatology", "Orthopedics", "Neurology"],
    "visit_type": ["Follow-up", "New", "New", "Emergency", "New", "Follow-up", "Emergency", "Follow-up"],
    "consultation_fee": [1200, 800, 1500, 2500, 2000, 800, 3000, 1800],
    "medicine_cost": [3500, 1200, 4200, 8500, 5000, 900, 9500, 2500],
    "insurance_covered": ["Yes", "No", "Yes", "Yes", "No", "Yes", "Yes", "No"],
})

patient_visits["total_treatment_cost"] = patient_visits["consultation_fee"] + patient_visits["medicine_cost"]
patient_visits["final_bill"] = patient_visits.apply(
    lambda x: x["total_treatment_cost"] * 0.80 if x["insurance_covered"] == "Yes" else x["total_treatment_cost"],
    axis=1,
)
patient_visits["age_risk_group"] = np.select(
    [patient_visits["age"] >= 60, patient_visits["age"] >= 30],
    ["Senior", "Adult"],
    default="Young",
)
patient_visits["high_cost_patient"] = patient_visits["final_bill"].apply(lambda x: "Yes" if x > 8000 else "No")

department_summary = patient_visits.groupby("department", as_index=False).agg(
    total_revenue=("final_bill", "sum"),
    average_bill=("final_bill", "mean"),
    patient_count=("patient_id", "count"),
)

print(patient_visits[[
    "patient_id", "patient_name", "department", "total_treatment_cost",
    "final_bill", "age_risk_group", "high_cost_patient"
]])
print(department_summary.round(2))`,
      howItWorks: [
        'Treatment cost combines consultation fee and medicine cost.',
        'Insurance discount is applied row by row with lambda.',
        'np.select classifies patients by age bands.',
        'High-cost patients are flagged from final_bill.',
        'GroupBy creates department revenue and patient count summaries.',
      ],
      commonMistake: undefined as { title: string; points: string[] } | undefined,
      observation: undefined as { title: string; points: string[] } | undefined,
      result: [
        { patient_id: '301', patient_name: 'Amit', department: 'Cardiology', total_treatment_cost: '4700', final_bill: '3760.0', age_risk_group: 'Adult', high_cost_patient: 'No' },
        { patient_id: '302', patient_name: 'Neha', department: 'Dermatology', total_treatment_cost: '2000', final_bill: '2000.0', age_risk_group: 'Young', high_cost_patient: 'No' },
        { patient_id: '303', patient_name: 'Suresh', department: 'Orthopedics', total_treatment_cost: '5700', final_bill: '4560.0', age_risk_group: 'Senior', high_cost_patient: 'No' },
        { patient_id: '304', patient_name: 'Kavita', department: 'Cardiology', total_treatment_cost: '11000', final_bill: '8800.0', age_risk_group: 'Adult', high_cost_patient: 'Yes' },
        { patient_id: '305', patient_name: 'Imran', department: 'Neurology', total_treatment_cost: '7000', final_bill: '7000.0', age_risk_group: 'Adult', high_cost_patient: 'No' },
        { patient_id: '306', patient_name: 'Ritu', department: 'Dermatology', total_treatment_cost: '1700', final_bill: '1360.0', age_risk_group: 'Adult', high_cost_patient: 'No' },
        { patient_id: '307', patient_name: 'Joseph', department: 'Orthopedics', total_treatment_cost: '12500', final_bill: '10000.0', age_risk_group: 'Senior', high_cost_patient: 'Yes' },
        { patient_id: '308', patient_name: 'Meenal', department: 'Neurology', total_treatment_cost: '4300', final_bill: '4300.0', age_risk_group: 'Young', high_cost_patient: 'No' },
      ] as Record<string, string>[],
    },
  },
  'python-drill-7': {
    id: 'python-drill-7',
    number: 7,
    title: 'Food Delivery Performance Analysis',
    tool: 'Python' as const,
    difficulty: 'Intermediate' as Difficulty,
    skills: ['Pandas', 'NumPy', 'Delivery Analytics', 'Lambda', 'GroupBy'],
    description: 'Analyze delivery efficiency, delay risk, delivery rating, and city-wise performance.',
    setup: 'Your dataset contains delivery_orders with promised and actual delivery times, order value, city, and delivery rating.',
    schema: {
      delivery_orders: schemaFrom([
        ['order_id', 'INT', 'Unique order ID'],
        ['customer_name', 'VARCHAR(50)', 'Customer name'],
        ['city', 'VARCHAR(50)', 'Delivery city'],
        ['restaurant_name', 'VARCHAR(50)', 'Restaurant name'],
        ['promised_time_min', 'INT', 'Promised delivery time in minutes'],
        ['actual_time_min', 'INT', 'Actual delivery time in minutes'],
        ['order_value', 'FLOAT', 'Total order value'],
        ['delivery_rating', 'FLOAT', 'Customer rating for delivery'],
      ]),
    },
    sampleTables: [
      table('delivery_orders', ['order_id', 'customer_name', 'city', 'restaurant_name', 'promised_time_min', 'actual_time_min', 'order_value', 'delivery_rating'], [
        [401, 'Aarav', 'Mumbai', 'Spice Hub', 35, 42, 650, 4.1],
        [402, 'Neha', 'Delhi', 'Urban Bites', 30, 28, 480, 4.7],
        [403, 'Rohan', 'Kolkata', 'Curry House', 40, 55, 720, 3.8],
        [404, 'Priya', 'Bangalore', 'Food Junction', 45, 43, 900, 4.5],
        [405, 'Kabir', 'Pune', 'Tandoori Tales', 35, 50, 560, 3.6],
        [406, 'Isha', 'Mumbai', 'Spice Hub', 30, 32, 430, 4.2],
        [407, 'Dev', 'Delhi', 'Urban Bites', 25, 35, 390, 3.9],
        [408, 'Meera', 'Kolkata', 'Curry House', 50, 48, 820, 4.6],
        [409, 'Arjun', 'Bangalore', 'Food Junction', 40, 60, 1050, 3.5],
        [410, 'Tara', 'Pune', 'Tandoori Tales', 45, 41, 700, 4.8],
      ]),
    ],
    departmentData: [] as { id: number; name: string }[],
    employeeData: [] as { id: number; name: string; salary: string; joining_date: string; department_id: number }[],
    task: 'Calculate delay minutes for each order.\nClassify delivery status as Early, On Time, Slight Delay, or Major Delay.\nIdentify poor delivery experience using delay and rating.\nAssign order value category as High, Medium, or Low.\nSummarize city-wise average delay, average rating, total order value, and delayed order count.',
    outputColumns: ['order_id', 'customer_name', 'city', 'delay_minutes', 'delivery_status', 'poor_experience', 'order_value_category'],
    expectedOutputPreview: [
      { order_id: '401', customer_name: 'Aarav', city: 'Mumbai', delay_minutes: '7', delivery_status: 'Slight Delay', poor_experience: 'No', order_value_category: 'Medium' },
      { order_id: '402', customer_name: 'Neha', city: 'Delhi', delay_minutes: '-2', delivery_status: 'Early', poor_experience: 'No', order_value_category: 'Low' },
      { order_id: '...', customer_name: '...', city: '...', delay_minutes: '...', delivery_status: '...', poor_experience: '...', order_value_category: '...' },
    ] as Record<string, string>[],
    hint: ['delay_minutes can be negative for early deliveries. Keep that signal instead of forcing it to zero.'],
    hintTitle: 'Python Hint',
    solution: {
      sql: `# Food Delivery Performance Analysis
import pandas as pd
import numpy as np

delivery_orders = pd.DataFrame({
    "order_id": [401, 402, 403, 404, 405, 406, 407, 408, 409, 410],
    "customer_name": ["Aarav", "Neha", "Rohan", "Priya", "Kabir", "Isha", "Dev", "Meera", "Arjun", "Tara"],
    "city": ["Mumbai", "Delhi", "Kolkata", "Bangalore", "Pune", "Mumbai", "Delhi", "Kolkata", "Bangalore", "Pune"],
    "restaurant_name": ["Spice Hub", "Urban Bites", "Curry House", "Food Junction", "Tandoori Tales", "Spice Hub", "Urban Bites", "Curry House", "Food Junction", "Tandoori Tales"],
    "promised_time_min": [35, 30, 40, 45, 35, 30, 25, 50, 40, 45],
    "actual_time_min": [42, 28, 55, 43, 50, 32, 35, 48, 60, 41],
    "order_value": [650, 480, 720, 900, 560, 430, 390, 820, 1050, 700],
    "delivery_rating": [4.1, 4.7, 3.8, 4.5, 3.6, 4.2, 3.9, 4.6, 3.5, 4.8],
})

delivery_orders["delay_minutes"] = delivery_orders["actual_time_min"] - delivery_orders["promised_time_min"]
delivery_orders["delivery_status"] = np.select(
    [
        delivery_orders["delay_minutes"] < 0,
        delivery_orders["delay_minutes"] == 0,
        delivery_orders["delay_minutes"] <= 10,
        delivery_orders["delay_minutes"] > 10,
    ],
    ["Early", "On Time", "Slight Delay", "Major Delay"],
    default="Unknown",
)
delivery_orders["poor_experience"] = delivery_orders.apply(
    lambda x: "Yes" if x["delay_minutes"] > 10 and x["delivery_rating"] < 4 else "No",
    axis=1,
)

def value_category(value):
    if value >= 800:
        return "High"
    if value >= 500:
        return "Medium"
    return "Low"

delivery_orders["order_value_category"] = delivery_orders["order_value"].apply(value_category)
city_summary = delivery_orders.groupby("city", as_index=False).agg(
    average_delay=("delay_minutes", "mean"),
    average_rating=("delivery_rating", "mean"),
    total_order_value=("order_value", "sum"),
    delayed_order_count=("delay_minutes", lambda x: (x > 0).sum()),
)

print(delivery_orders[[
    "order_id", "customer_name", "city", "delay_minutes",
    "delivery_status", "poor_experience", "order_value_category"
]])
print(city_summary.round(2))`,
      howItWorks: [
        'Delay minutes compares actual delivery time with promised time.',
        'np.select maps delay values to delivery status labels.',
        'Poor experience combines major delay with rating below 4.',
        'A custom function buckets order value into High, Medium, or Low.',
        'City-level GroupBy summarizes operational performance.',
      ],
      commonMistake: undefined as { title: string; points: string[] } | undefined,
      observation: undefined as { title: string; points: string[] } | undefined,
      result: [
        { order_id: '401', customer_name: 'Aarav', city: 'Mumbai', delay_minutes: '7', delivery_status: 'Slight Delay', poor_experience: 'No', order_value_category: 'Medium' },
        { order_id: '402', customer_name: 'Neha', city: 'Delhi', delay_minutes: '-2', delivery_status: 'Early', poor_experience: 'No', order_value_category: 'Low' },
        { order_id: '403', customer_name: 'Rohan', city: 'Kolkata', delay_minutes: '15', delivery_status: 'Major Delay', poor_experience: 'Yes', order_value_category: 'Medium' },
        { order_id: '404', customer_name: 'Priya', city: 'Bangalore', delay_minutes: '-2', delivery_status: 'Early', poor_experience: 'No', order_value_category: 'High' },
        { order_id: '405', customer_name: 'Kabir', city: 'Pune', delay_minutes: '15', delivery_status: 'Major Delay', poor_experience: 'Yes', order_value_category: 'Medium' },
        { order_id: '406', customer_name: 'Isha', city: 'Mumbai', delay_minutes: '2', delivery_status: 'Slight Delay', poor_experience: 'No', order_value_category: 'Low' },
        { order_id: '407', customer_name: 'Dev', city: 'Delhi', delay_minutes: '10', delivery_status: 'Slight Delay', poor_experience: 'No', order_value_category: 'Low' },
        { order_id: '408', customer_name: 'Meera', city: 'Kolkata', delay_minutes: '-2', delivery_status: 'Early', poor_experience: 'No', order_value_category: 'High' },
        { order_id: '409', customer_name: 'Arjun', city: 'Bangalore', delay_minutes: '20', delivery_status: 'Major Delay', poor_experience: 'Yes', order_value_category: 'High' },
        { order_id: '410', customer_name: 'Tara', city: 'Pune', delay_minutes: '-4', delivery_status: 'Early', poor_experience: 'No', order_value_category: 'Medium' },
      ] as Record<string, string>[],
    },
  },
  'python-drill-8': {
    id: 'python-drill-8',
    number: 8,
    title: 'Website Traffic Quality Analysis',
    tool: 'Python' as const,
    difficulty: 'Intermediate' as Difficulty,
    skills: ['Pandas', 'NumPy', 'Website Analytics', 'Lambda', 'GroupBy'],
    description: 'Analyze website traffic quality by identifying bounce risk, engagement level, and traffic source performance.',
    setup: 'Your dataset contains website_sessions with source, device, page views, session duration, and conversion status.',
    schema: {
      website_sessions: schemaFrom([
        ['session_id', 'INT', 'Unique session ID'],
        ['user_id', 'INT', 'Unique user ID'],
        ['traffic_source', 'VARCHAR(50)', 'Source of website traffic'],
        ['device_type', 'VARCHAR(30)', 'Device used by visitor'],
        ['page_views', 'INT', 'Number of pages viewed'],
        ['session_duration_sec', 'INT', 'Session duration in seconds'],
        ['converted', 'VARCHAR(5)', 'Whether the user converted'],
      ]),
    },
    sampleTables: [
      table('website_sessions', ['session_id', 'user_id', 'traffic_source', 'device_type', 'page_views', 'session_duration_sec', 'converted'], [
        [501, 1001, 'Google', 'Mobile', 5, 320, 'Yes'],
        [502, 1002, 'Facebook', 'Desktop', 2, 80, 'No'],
        [503, 1003, 'Direct', 'Mobile', 1, 25, 'No'],
        [504, 1004, 'Google', 'Desktop', 7, 540, 'Yes'],
        [505, 1005, 'Instagram', 'Mobile', 3, 150, 'No'],
        [506, 1006, 'Facebook', 'Mobile', 4, 210, 'Yes'],
        [507, 1007, 'Direct', 'Desktop', 1, 40, 'No'],
        [508, 1008, 'Instagram', 'Desktop', 6, 410, 'Yes'],
        [509, 1009, 'Google', 'Mobile', 2, 95, 'No'],
        [510, 1010, 'Facebook', 'Desktop', 5, 300, 'Yes'],
      ]),
    ],
    departmentData: [] as { id: number; name: string }[],
    employeeData: [] as { id: number; name: string; salary: string; joining_date: string; department_id: number }[],
    task: 'Calculate engagement score for each session.\nClassify sessions as High, Medium, or Low engagement.\nIdentify bounce risk using page views and session duration.\nConvert Yes/No conversion values into numeric conversion flags.\nSummarize traffic source-wise sessions, average engagement score, bounce count, and conversion rate.',
    outputColumns: ['session_id', 'traffic_source', 'device_type', 'engagement_score', 'engagement_level', 'bounce_risk', 'conversion_flag'],
    expectedOutputPreview: [
      { session_id: '501', traffic_source: 'Google', device_type: 'Mobile', engagement_score: '82.0', engagement_level: 'High', bounce_risk: 'No', conversion_flag: '1' },
      { session_id: '502', traffic_source: 'Facebook', device_type: 'Desktop', engagement_score: '28.0', engagement_level: 'Low', bounce_risk: 'Yes', conversion_flag: '0' },
      { session_id: '...', traffic_source: '...', device_type: '...', engagement_score: '...', engagement_level: '...', bounce_risk: '...', conversion_flag: '...' },
    ] as Record<string, string>[],
    hint: ['Calculate conversion_flag before groupby so conversion_rate_pct can use mean().'],
    hintTitle: 'Python Hint',
    solution: {
      sql: `# Website Traffic Quality Analysis
import pandas as pd
import numpy as np

website_sessions = pd.DataFrame({
    "session_id": [501, 502, 503, 504, 505, 506, 507, 508, 509, 510],
    "user_id": [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010],
    "traffic_source": ["Google", "Facebook", "Direct", "Google", "Instagram", "Facebook", "Direct", "Instagram", "Google", "Facebook"],
    "device_type": ["Mobile", "Desktop", "Mobile", "Desktop", "Mobile", "Mobile", "Desktop", "Desktop", "Mobile", "Desktop"],
    "page_views": [5, 2, 1, 7, 3, 4, 1, 6, 2, 5],
    "session_duration_sec": [320, 80, 25, 540, 150, 210, 40, 410, 95, 300],
    "converted": ["Yes", "No", "No", "Yes", "No", "Yes", "No", "Yes", "No", "Yes"],
})

website_sessions["engagement_score"] = (website_sessions["page_views"] * 10 + website_sessions["session_duration_sec"] / 10).round(2)
website_sessions["engagement_level"] = np.select(
    [website_sessions["engagement_score"] >= 80, website_sessions["engagement_score"] >= 40],
    ["High", "Medium"],
    default="Low",
)
website_sessions["bounce_risk"] = website_sessions.apply(
    lambda x: "Yes" if x["page_views"] <= 2 and x["session_duration_sec"] < 100 else "No",
    axis=1,
)
website_sessions["conversion_flag"] = website_sessions["converted"].apply(lambda x: 1 if x == "Yes" else 0)

traffic_summary = website_sessions.groupby("traffic_source", as_index=False).agg(
    total_sessions=("session_id", "count"),
    average_engagement_score=("engagement_score", "mean"),
    bounce_count=("bounce_risk", lambda x: (x == "Yes").sum()),
    conversion_rate_pct=("conversion_flag", "mean"),
)
traffic_summary["conversion_rate_pct"] = (traffic_summary["conversion_rate_pct"] * 100).round(2)

print(website_sessions[[
    "session_id", "traffic_source", "device_type", "engagement_score",
    "engagement_level", "bounce_risk", "conversion_flag"
]])
print(traffic_summary.round(2))`,
      howItWorks: [
        'Engagement score combines page depth and session duration.',
        'np.select labels engagement as High, Medium, or Low.',
        'Bounce risk uses low page views and short duration.',
        'Yes/No conversions become numeric flags for aggregation.',
        'Traffic-source GroupBy calculates source quality metrics.',
      ],
      commonMistake: undefined as { title: string; points: string[] } | undefined,
      observation: undefined as { title: string; points: string[] } | undefined,
      result: [
        { session_id: '501', traffic_source: 'Google', device_type: 'Mobile', engagement_score: '82.0', engagement_level: 'High', bounce_risk: 'No', conversion_flag: '1' },
        { session_id: '502', traffic_source: 'Facebook', device_type: 'Desktop', engagement_score: '28.0', engagement_level: 'Low', bounce_risk: 'Yes', conversion_flag: '0' },
        { session_id: '503', traffic_source: 'Direct', device_type: 'Mobile', engagement_score: '12.5', engagement_level: 'Low', bounce_risk: 'Yes', conversion_flag: '0' },
        { session_id: '504', traffic_source: 'Google', device_type: 'Desktop', engagement_score: '124.0', engagement_level: 'High', bounce_risk: 'No', conversion_flag: '1' },
        { session_id: '505', traffic_source: 'Instagram', device_type: 'Mobile', engagement_score: '45.0', engagement_level: 'Medium', bounce_risk: 'No', conversion_flag: '0' },
        { session_id: '506', traffic_source: 'Facebook', device_type: 'Mobile', engagement_score: '61.0', engagement_level: 'Medium', bounce_risk: 'No', conversion_flag: '1' },
        { session_id: '507', traffic_source: 'Direct', device_type: 'Desktop', engagement_score: '14.0', engagement_level: 'Low', bounce_risk: 'Yes', conversion_flag: '0' },
        { session_id: '508', traffic_source: 'Instagram', device_type: 'Desktop', engagement_score: '101.0', engagement_level: 'High', bounce_risk: 'No', conversion_flag: '1' },
        { session_id: '509', traffic_source: 'Google', device_type: 'Mobile', engagement_score: '29.5', engagement_level: 'Low', bounce_risk: 'Yes', conversion_flag: '0' },
        { session_id: '510', traffic_source: 'Facebook', device_type: 'Desktop', engagement_score: '80.0', engagement_level: 'High', bounce_risk: 'No', conversion_flag: '1' },
      ] as Record<string, string>[],
    },
  },
  'python-drill-9': {
    id: 'python-drill-9',
    number: 9,
    title: 'Insurance Claim Severity Analysis',
    tool: 'Python' as const,
    difficulty: 'Intermediate' as Difficulty,
    skills: ['Pandas', 'NumPy', 'Insurance Analytics', 'Lambda', 'GroupBy'],
    description: 'Analyze insurance claims, classify claim severity, calculate settlement gaps, and summarize policy-type risk.',
    setup: 'Your dataset contains insurance_claims with claim amount, approved amount, claim days, policy type, and fraud flag.',
    schema: {
      insurance_claims: schemaFrom([
        ['claim_id', 'INT', 'Unique claim ID'],
        ['policyholder_name', 'VARCHAR(50)', 'Name of policyholder'],
        ['policy_type', 'VARCHAR(50)', 'Type of insurance policy'],
        ['claim_amount', 'FLOAT', 'Amount claimed by policyholder'],
        ['approved_amount', 'FLOAT', 'Amount approved by insurer'],
        ['claim_days', 'INT', 'Number of days taken to process claim'],
        ['fraud_flag', 'VARCHAR(5)', 'Whether claim is suspected fraud'],
      ]),
    },
    sampleTables: [
      table('insurance_claims', ['claim_id', 'policyholder_name', 'policy_type', 'claim_amount', 'approved_amount', 'claim_days', 'fraud_flag'], [
        [601, 'Amit', 'Health', 85000, 78000, 12, 'No'],
        [602, 'Neha', 'Motor', 45000, 30000, 20, 'No'],
        [603, 'Rohan', 'Travel', 18000, 16000, 7, 'No'],
        [604, 'Priya', 'Health', 125000, 90000, 25, 'Yes'],
        [605, 'Kabir', 'Motor', 60000, 52000, 15, 'No'],
        [606, 'Isha', 'Travel', 22000, 12000, 18, 'Yes'],
        [607, 'Dev', 'Health', 95000, 88000, 10, 'No'],
        [608, 'Meera', 'Motor', 70000, 45000, 30, 'Yes'],
      ]),
    ],
    departmentData: [] as { id: number; name: string }[],
    employeeData: [] as { id: number; name: string; salary: string; joining_date: string; department_id: number }[],
    task: 'Calculate settlement gap for each claim.\nCalculate approval percentage for each claim.\nClassify claim severity as High, Medium, or Low.\nIdentify high-risk claims using fraud flag and claim processing days.\nSummarize policy-type-wise claim amount, approved amount, average approval percentage, and high-risk claim count.',
    outputColumns: ['claim_id', 'policyholder_name', 'policy_type', 'settlement_gap', 'approval_percentage', 'claim_severity', 'high_risk_claim'],
    expectedOutputPreview: [
      { claim_id: '601', policyholder_name: 'Amit', policy_type: 'Health', settlement_gap: '7000', approval_percentage: '91.76', claim_severity: 'High', high_risk_claim: 'No' },
      { claim_id: '602', policyholder_name: 'Neha', policy_type: 'Motor', settlement_gap: '15000', approval_percentage: '66.67', claim_severity: 'Medium', high_risk_claim: 'No' },
      { claim_id: '...', policyholder_name: '...', policy_type: '...', settlement_gap: '...', approval_percentage: '...', claim_severity: '...', high_risk_claim: '...' },
    ] as Record<string, string>[],
    hint: ['Use claim_amount thresholds for severity and fraud_flag or claim_days for high-risk classification.'],
    hintTitle: 'Python Hint',
    solution: {
      sql: `# Insurance Claim Severity Analysis
import pandas as pd
import numpy as np

insurance_claims = pd.DataFrame({
    "claim_id": [601, 602, 603, 604, 605, 606, 607, 608],
    "policyholder_name": ["Amit", "Neha", "Rohan", "Priya", "Kabir", "Isha", "Dev", "Meera"],
    "policy_type": ["Health", "Motor", "Travel", "Health", "Motor", "Travel", "Health", "Motor"],
    "claim_amount": [85000, 45000, 18000, 125000, 60000, 22000, 95000, 70000],
    "approved_amount": [78000, 30000, 16000, 90000, 52000, 12000, 88000, 45000],
    "claim_days": [12, 20, 7, 25, 15, 18, 10, 30],
    "fraud_flag": ["No", "No", "No", "Yes", "No", "Yes", "No", "Yes"],
})

insurance_claims["settlement_gap"] = insurance_claims["claim_amount"] - insurance_claims["approved_amount"]
insurance_claims["approval_percentage"] = (insurance_claims["approved_amount"] / insurance_claims["claim_amount"] * 100).round(2)
insurance_claims["claim_severity"] = np.select(
    [insurance_claims["claim_amount"] >= 80000, insurance_claims["claim_amount"] >= 40000],
    ["High", "Medium"],
    default="Low",
)
insurance_claims["high_risk_claim"] = insurance_claims.apply(
    lambda x: "Yes" if x["fraud_flag"] == "Yes" or x["claim_days"] > 20 else "No",
    axis=1,
)
policy_summary = insurance_claims.groupby("policy_type", as_index=False).agg(
    total_claim_amount=("claim_amount", "sum"),
    total_approved_amount=("approved_amount", "sum"),
    average_approval_percentage=("approval_percentage", "mean"),
    high_risk_claim_count=("high_risk_claim", lambda x: (x == "Yes").sum()),
)

print(insurance_claims[[
    "claim_id", "policyholder_name", "policy_type", "settlement_gap",
    "approval_percentage", "claim_severity", "high_risk_claim"
]])
print(policy_summary.round(2))`,
      howItWorks: [
        'Settlement gap compares requested and approved claim amount.',
        'Approval percentage expresses approved value as a percentage of claim amount.',
        'np.select creates claim severity labels from claim amount thresholds.',
        'High-risk claims combine suspected fraud and processing delay.',
        'GroupBy summarizes risk and approval metrics by policy type.',
      ],
      commonMistake: undefined as { title: string; points: string[] } | undefined,
      observation: undefined as { title: string; points: string[] } | undefined,
      result: [
        { claim_id: '601', policyholder_name: 'Amit', policy_type: 'Health', settlement_gap: '7000', approval_percentage: '91.76', claim_severity: 'High', high_risk_claim: 'No' },
        { claim_id: '602', policyholder_name: 'Neha', policy_type: 'Motor', settlement_gap: '15000', approval_percentage: '66.67', claim_severity: 'Medium', high_risk_claim: 'No' },
        { claim_id: '603', policyholder_name: 'Rohan', policy_type: 'Travel', settlement_gap: '2000', approval_percentage: '88.89', claim_severity: 'Low', high_risk_claim: 'No' },
        { claim_id: '604', policyholder_name: 'Priya', policy_type: 'Health', settlement_gap: '35000', approval_percentage: '72.00', claim_severity: 'High', high_risk_claim: 'Yes' },
        { claim_id: '605', policyholder_name: 'Kabir', policy_type: 'Motor', settlement_gap: '8000', approval_percentage: '86.67', claim_severity: 'Medium', high_risk_claim: 'No' },
        { claim_id: '606', policyholder_name: 'Isha', policy_type: 'Travel', settlement_gap: '10000', approval_percentage: '54.55', claim_severity: 'Low', high_risk_claim: 'Yes' },
        { claim_id: '607', policyholder_name: 'Dev', policy_type: 'Health', settlement_gap: '7000', approval_percentage: '92.63', claim_severity: 'High', high_risk_claim: 'No' },
        { claim_id: '608', policyholder_name: 'Meera', policy_type: 'Motor', settlement_gap: '25000', approval_percentage: '64.29', claim_severity: 'Medium', high_risk_claim: 'Yes' },
      ] as Record<string, string>[],
    },
  },
  'python-drill-10': {
    id: 'python-drill-10',
    number: 10,
    title: 'Hotel Booking Cancellation Analysis',
    tool: 'Python' as const,
    difficulty: 'Intermediate' as Difficulty,
    skills: ['Pandas', 'NumPy', 'Date Handling', 'Hotel Analytics', 'GroupBy'],
    description: 'Analyze hotel bookings, cancellation risk, revenue loss, stay duration, and hotel-wise booking performance.',
    setup: 'Your dataset contains hotel_bookings with check-in and check-out dates, room rate, hotel type, and booking status.',
    schema: {
      hotel_bookings: schemaFrom([
        ['booking_id', 'INT', 'Unique booking ID'],
        ['guest_name', 'VARCHAR(50)', 'Guest name'],
        ['hotel_type', 'VARCHAR(50)', 'Type of hotel'],
        ['check_in_date', 'DATE', 'Guest check-in date'],
        ['check_out_date', 'DATE', 'Guest check-out date'],
        ['room_rate', 'FLOAT', 'Room rate per night'],
        ['booking_status', 'VARCHAR(20)', 'Booking status'],
      ]),
    },
    sampleTables: [
      table('hotel_bookings', ['booking_id', 'guest_name', 'hotel_type', 'check_in_date', 'check_out_date', 'room_rate', 'booking_status'], [
        [701, 'Amit', 'Business Hotel', '2024-03-01', '2024-03-04', 4500, 'Completed'],
        [702, 'Neha', 'Resort', '2024-03-05', '2024-03-10', 7500, 'Cancelled'],
        [703, 'Rohan', 'Budget Hotel', '2024-03-08', '2024-03-10', 2200, 'Completed'],
        [704, 'Priya', 'Business Hotel', '2024-03-12', '2024-03-15', 5000, 'Completed'],
        [705, 'Kabir', 'Resort', '2024-03-14', '2024-03-20', 8200, 'Cancelled'],
        [706, 'Isha', 'Budget Hotel', '2024-03-16', '2024-03-18', 2500, 'Completed'],
        [707, 'Dev', 'Business Hotel', '2024-03-18', '2024-03-22', 4800, 'Cancelled'],
        [708, 'Meera', 'Resort', '2024-03-21', '2024-03-25', 7800, 'Completed'],
      ]),
    ],
    departmentData: [] as { id: number; name: string }[],
    employeeData: [] as { id: number; name: string; salary: string; joining_date: string; department_id: number }[],
    task: 'Calculate stay duration for each booking.\nCalculate potential revenue for every booking.\nCalculate revenue loss for cancelled bookings.\nClassify booking risk as High Risk, Medium Risk, or Low Risk.\nSummarize hotel-type-wise total bookings, completed bookings, cancelled bookings, potential revenue, and revenue loss.',
    outputColumns: ['booking_id', 'guest_name', 'hotel_type', 'stay_duration', 'potential_revenue', 'revenue_loss', 'booking_risk'],
    expectedOutputPreview: [
      { booking_id: '701', guest_name: 'Amit', hotel_type: 'Business Hotel', stay_duration: '3', potential_revenue: '13500', revenue_loss: '0', booking_risk: 'Low Risk' },
      { booking_id: '702', guest_name: 'Neha', hotel_type: 'Resort', stay_duration: '5', potential_revenue: '37500', revenue_loss: '37500', booking_risk: 'Medium Risk' },
      { booking_id: '...', guest_name: '...', hotel_type: '...', stay_duration: '...', potential_revenue: '...', revenue_loss: '...', booking_risk: '...' },
    ] as Record<string, string>[],
    hint: ['Convert date columns with pd.to_datetime before subtracting them.'],
    hintTitle: 'Python Hint',
    solution: {
      sql: `# Hotel Booking Cancellation Analysis
import pandas as pd
import numpy as np

hotel_bookings = pd.DataFrame({
    "booking_id": [701, 702, 703, 704, 705, 706, 707, 708],
    "guest_name": ["Amit", "Neha", "Rohan", "Priya", "Kabir", "Isha", "Dev", "Meera"],
    "hotel_type": ["Business Hotel", "Resort", "Budget Hotel", "Business Hotel", "Resort", "Budget Hotel", "Business Hotel", "Resort"],
    "check_in_date": ["2024-03-01", "2024-03-05", "2024-03-08", "2024-03-12", "2024-03-14", "2024-03-16", "2024-03-18", "2024-03-21"],
    "check_out_date": ["2024-03-04", "2024-03-10", "2024-03-10", "2024-03-15", "2024-03-20", "2024-03-18", "2024-03-22", "2024-03-25"],
    "room_rate": [4500, 7500, 2200, 5000, 8200, 2500, 4800, 7800],
    "booking_status": ["Completed", "Cancelled", "Completed", "Completed", "Cancelled", "Completed", "Cancelled", "Completed"],
})

hotel_bookings["check_in_date"] = pd.to_datetime(hotel_bookings["check_in_date"])
hotel_bookings["check_out_date"] = pd.to_datetime(hotel_bookings["check_out_date"])
hotel_bookings["stay_duration"] = (hotel_bookings["check_out_date"] - hotel_bookings["check_in_date"]).dt.days
hotel_bookings["potential_revenue"] = hotel_bookings["stay_duration"] * hotel_bookings["room_rate"]
hotel_bookings["revenue_loss"] = hotel_bookings.apply(
    lambda x: x["potential_revenue"] if x["booking_status"] == "Cancelled" else 0,
    axis=1,
)
hotel_bookings["booking_risk"] = np.select(
    [
        (hotel_bookings["booking_status"] == "Cancelled") & (hotel_bookings["potential_revenue"] >= 40000),
        hotel_bookings["booking_status"] == "Cancelled",
    ],
    ["High Risk", "Medium Risk"],
    default="Low Risk",
)
hotel_summary = hotel_bookings.groupby("hotel_type", as_index=False).agg(
    total_bookings=("booking_id", "count"),
    completed_bookings=("booking_status", lambda x: (x == "Completed").sum()),
    cancelled_bookings=("booking_status", lambda x: (x == "Cancelled").sum()),
    total_potential_revenue=("potential_revenue", "sum"),
    total_revenue_loss=("revenue_loss", "sum"),
)

print(hotel_bookings[[
    "booking_id", "guest_name", "hotel_type", "stay_duration",
    "potential_revenue", "revenue_loss", "booking_risk"
]])
print(hotel_summary)`,
      howItWorks: [
        'Date conversion enables check-out minus check-in calculations.',
        'Stay duration multiplied by room rate gives potential revenue.',
        'Revenue loss is counted only for cancelled bookings.',
        'np.select classifies cancellation risk from status and revenue exposure.',
        'Hotel-type GroupBy summarizes bookings, cancellations, and revenue loss.',
      ],
      commonMistake: undefined as { title: string; points: string[] } | undefined,
      observation: undefined as { title: string; points: string[] } | undefined,
      result: [
        { booking_id: '701', guest_name: 'Amit', hotel_type: 'Business Hotel', stay_duration: '3', potential_revenue: '13500', revenue_loss: '0', booking_risk: 'Low Risk' },
        { booking_id: '702', guest_name: 'Neha', hotel_type: 'Resort', stay_duration: '5', potential_revenue: '37500', revenue_loss: '37500', booking_risk: 'Medium Risk' },
        { booking_id: '703', guest_name: 'Rohan', hotel_type: 'Budget Hotel', stay_duration: '2', potential_revenue: '4400', revenue_loss: '0', booking_risk: 'Low Risk' },
        { booking_id: '704', guest_name: 'Priya', hotel_type: 'Business Hotel', stay_duration: '3', potential_revenue: '15000', revenue_loss: '0', booking_risk: 'Low Risk' },
        { booking_id: '705', guest_name: 'Kabir', hotel_type: 'Resort', stay_duration: '6', potential_revenue: '49200', revenue_loss: '49200', booking_risk: 'High Risk' },
        { booking_id: '706', guest_name: 'Isha', hotel_type: 'Budget Hotel', stay_duration: '2', potential_revenue: '5000', revenue_loss: '0', booking_risk: 'Low Risk' },
        { booking_id: '707', guest_name: 'Dev', hotel_type: 'Business Hotel', stay_duration: '4', potential_revenue: '19200', revenue_loss: '19200', booking_risk: 'Medium Risk' },
        { booking_id: '708', guest_name: 'Meera', hotel_type: 'Resort', stay_duration: '4', potential_revenue: '31200', revenue_loss: '0', booking_risk: 'Low Risk' },
      ] as Record<string, string>[],
    },
  },
  'python-drill-11': {
    id: 'python-drill-11',
    number: 11,
    title: 'Customer Churn Prediction Strategy',
    tool: 'AI/ML' as const,
    difficulty: 'Intermediate' as Difficulty,
    skills: ['Machine Learning', 'Classification', 'Feature Engineering', 'Evaluation Metrics', 'SHAP'],
    description: 'Design a predictive churn strategy for a telecom company whose churn increased from 8% to 15%.',
    setup: 'A telecom company wants to identify customers likely to churn in the next 30 days so that the retention team can intervene proactively.',
    schema: {
      customer_data: schemaFrom([
        ['customer_id', 'INT', 'Unique customer identifier'],
        ['tenure_months', 'INT', 'Customer tenure in months'],
        ['monthly_bill', 'FLOAT', 'Average monthly bill amount'],
        ['support_tickets', 'INT', 'Number of support tickets raised'],
        ['late_payments', 'INT', 'Number of late payments'],
        ['contract_type', 'VARCHAR(20)', 'Monthly / Annual'],
        ['internet_type', 'VARCHAR(20)', 'Fiber / DSL / Cable'],
        ['customer_satisfaction', 'INT', 'Satisfaction score from 1 to 10'],
        ['churn', 'VARCHAR(5)', 'Whether customer churned'],
      ]),
    },
    sampleTables: [
      table('customer_data', ['customer_id', 'tenure_months', 'monthly_bill', 'support_tickets', 'late_payments', 'contract_type', 'internet_type', 'customer_satisfaction', 'churn'], [
        [1001, 36, 120, 1, 0, 'Annual', 'Fiber', 9, 'No'],
        [1002, 4, 95, 6, 3, 'Monthly', 'DSL', 4, 'Yes'],
        [1003, 18, 80, 2, 1, 'Monthly', 'Cable', 7, 'No'],
        [1004, 2, 150, 8, 4, 'Monthly', 'Fiber', 3, 'Yes'],
        [1005, 48, 110, 0, 0, 'Annual', 'Fiber', 10, 'No'],
      ]),
      table('Strong Predictive Features', ['Feature', 'Why'], [
        ['tenure_months', 'New customers often churn more'],
        ['support_tickets', 'High complaints indicate dissatisfaction'],
        ['customer_satisfaction', 'Direct measure of experience'],
        ['late_payments', 'Financial stress indicator'],
        ['contract_type', 'Monthly plans generally churn more'],
        ['monthly_bill', 'High bills may increase churn risk'],
      ]),
    ],
    departmentData: [] as { id: number; name: string }[],
    employeeData: [] as { id: number; name: string; salary: string; joining_date: string; department_id: number }[],
    task: 'Answer the churn modeling case:\nWhat type of Machine Learning problem is this?\nWhich features are likely to be strong predictors of churn?\nWhich features require preprocessing?\nWhich ML algorithms would you consider?\nWhich evaluation metrics should be used?\nHow would you handle class imbalance?\nHow would you explain model predictions to business leaders?\nWhat business actions would you recommend based on the model output?',
    outputColumns: ['Question', 'Expected Answer'],
    expectedOutputPreview: [
      { Question: 'Problem Type', 'Expected Answer': 'Binary Classification' },
      { Question: 'Target Variable', 'Expected Answer': 'Churn' },
      { Question: '...', 'Expected Answer': '...' },
    ] as Record<string, string>[],
    hint: ['Treat churn as a supervised binary classification problem and prioritize recall because missing likely churners is costly.'],
    hintTitle: 'Interview Hint',
    solution: {
      sql: `Customer Churn Prediction Strategy

1. Problem Type
Supervised learning, binary classification.
Target variable: churn = Yes / No.

2. Strong Predictive Features
tenure_months, support_tickets, customer_satisfaction, late_payments, contract_type, and monthly_bill.

3. Preprocessing
Encode contract_type and internet_type with one-hot encoding.
Impute missing numeric values with median and categorical values with mode.
Scale numeric features such as monthly_bill, tenure_months, support_tickets, and late_payments.

4. Models
Baseline: Logistic Regression.
Advanced: Random Forest, XGBoost, LightGBM, CatBoost.
Preferred production model: XGBoost because it performs well, handles nonlinearity, and supports feature importance.

5. Evaluation Metrics
Avoid relying only on accuracy because churn is imbalanced.
Use precision, recall, F1 score, and ROC-AUC.
Prioritize recall because missing a churn customer is expensive.

6. Class Imbalance
Use SMOTE, class weighting, random oversampling, or balanced XGBoost.
Recommended approach: SMOTE + XGBoost.

7. Explainability
Use SHAP, feature importance, and partial dependence plots.
Example: customers with more than 5 support tickets, satisfaction below 5, and monthly contracts are much more likely to churn.

8. Business Actions
For churn probability above 70%: retention calls, discount offers, free upgrades, loyalty rewards, and dedicated support.
For churn probability from 40% to 70%: email campaigns, product education, and satisfaction surveys.`,
      howItWorks: [
        'The target has two classes, so the business problem maps to binary classification.',
        'Predictive features combine behavior, payment stress, support friction, and contract commitment.',
        'Categorical variables need encoding and numeric variables may need imputation/scaling.',
        'Recall is the key metric because false negatives mean missed retention opportunities.',
        'SHAP translates model behavior into business-friendly explanations.',
      ],
      commonMistake: {
        title: 'Using Accuracy Alone',
        points: [
          'If churn is 15%, a model can predict No Churn for everyone and still show 85% accuracy.',
          'Use recall, F1, precision, and ROC-AUC to evaluate the model properly.',
        ],
      } as { title: string; points: string[] } | undefined,
      observation: {
        title: 'Business Framing',
        points: [
          'The model should trigger retention actions, not just produce a probability score.',
          'Risk bands make predictions easier for sales and support teams to use.',
        ],
      } as { title: string; points: string[] } | undefined,
      result: [
        { Question: 'Problem Type', 'Expected Answer': 'Binary Classification' },
        { Question: 'Target Variable', 'Expected Answer': 'Churn' },
        { Question: 'Best Baseline Model', 'Expected Answer': 'Logistic Regression' },
        { Question: 'Best Advanced Model', 'Expected Answer': 'XGBoost' },
        { Question: 'Most Important Metric', 'Expected Answer': 'Recall' },
        { Question: 'Class Imbalance Solution', 'Expected Answer': 'SMOTE / Class Weighting' },
        { Question: 'Explainability Tool', 'Expected Answer': 'SHAP' },
        { Question: 'Business Goal', 'Expected Answer': 'Reduce Customer Churn' },
      ] as Record<string, string>[],
    },
  },
  'python-drill-12': {
    id: 'python-drill-12',
    number: 12,
    title: 'Subscription Pricing A/B Test Analysis',
    tool: 'Python' as const,
    difficulty: 'Intermediate' as Difficulty,
    skills: ['Pandas', 'Statistics', 'A/B Testing', 'Hypothesis Testing', 'Confidence Interval'],
    description: 'Analyze whether a new subscription pricing page improves conversion rate using Python, statistics, and business interpretation.',
    setup: 'A subscription business launched a Treatment pricing page against the old Control page and wants to compare conversion and revenue outcomes.',
    schema: {
      pricing_experiment: schemaFrom([
        ['user_id', 'INT', 'Unique user ID'],
        ['variant', 'VARCHAR(20)', 'Pricing page shown to the user'],
        ['visits', 'INT', 'Number of visits by the user'],
        ['converted', 'INT', 'Whether the user purchased subscription'],
        ['revenue', 'FLOAT', 'Revenue generated from the user'],
        ['device_type', 'VARCHAR(30)', 'Device used by the user'],
        ['traffic_source', 'VARCHAR(50)', 'Source of traffic'],
      ]),
    },
    sampleTables: [
      table('pricing_experiment', ['user_id', 'variant', 'visits', 'converted', 'revenue', 'device_type', 'traffic_source'], [
        [1001, 'Control', 2, 0, 0, 'Mobile', 'Google'],
        [1002, 'Control', 1, 1, 999, 'Desktop', 'Direct'],
        [1003, 'Control', 3, 0, 0, 'Mobile', 'Instagram'],
        [1004, 'Control', 2, 1, 999, 'Desktop', 'Google'],
        [1005, 'Control', 1, 0, 0, 'Mobile', 'Facebook'],
        [1006, 'Treatment', 2, 1, 1199, 'Mobile', 'Google'],
        [1007, 'Treatment', 1, 1, 1199, 'Desktop', 'Direct'],
        [1008, 'Treatment', 3, 0, 0, 'Mobile', 'Instagram'],
        [1009, 'Treatment', 2, 1, 1199, 'Desktop', 'Google'],
        [1010, 'Treatment', 1, 0, 0, 'Mobile', 'Facebook'],
        [1011, 'Control', 2, 0, 0, 'Desktop', 'Direct'],
        [1012, 'Treatment', 2, 1, 1199, 'Mobile', 'Google'],
      ]),
    ],
    departmentData: [] as { id: number; name: string }[],
    employeeData: [] as { id: number; name: string; salary: string; joining_date: string; department_id: number }[],
    task: 'Calculate conversion rate for Control and Treatment.\nCalculate revenue per visitor for both groups.\nCalculate absolute and relative uplift in conversion rate.\nTest whether Treatment is statistically better than Control.\nCalculate the 95% confidence interval for uplift.\nRecommend whether the business should roll out the new pricing page.',
    outputColumns: ['variant', 'total_users', 'conversions', 'total_revenue', 'conversion_rate', 'revenue_per_visitor'],
    expectedOutputPreview: [
      { variant: 'Control', total_users: '6', conversions: '2', total_revenue: '1998', conversion_rate: '0.3333', revenue_per_visitor: '333.00' },
      { variant: 'Treatment', total_users: '6', conversions: '4', total_revenue: '4796', conversion_rate: '0.6667', revenue_per_visitor: '799.33' },
    ] as Record<string, string>[],
    hint: ['Use a two-proportion z-test for conversion rate comparison, but discuss sample size risk in the business recommendation.'],
    hintTitle: 'Statistics Hint',
    solution: {
      sql: `# Subscription Pricing A/B Test Analysis
import pandas as pd
import numpy as np
from statsmodels.stats.proportion import proportions_ztest, confint_proportions_2indep

pricing_experiment = pd.DataFrame({
    "user_id": [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012],
    "variant": ["Control", "Control", "Control", "Control", "Control", "Treatment", "Treatment", "Treatment", "Treatment", "Treatment", "Control", "Treatment"],
    "visits": [2, 1, 3, 2, 1, 2, 1, 3, 2, 1, 2, 2],
    "converted": [0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1],
    "revenue": [0, 999, 0, 999, 0, 1199, 1199, 0, 1199, 0, 0, 1199],
    "device_type": ["Mobile", "Desktop", "Mobile", "Desktop", "Mobile", "Mobile", "Desktop", "Mobile", "Desktop", "Mobile", "Desktop", "Mobile"],
    "traffic_source": ["Google", "Direct", "Instagram", "Google", "Facebook", "Google", "Direct", "Instagram", "Google", "Facebook", "Direct", "Google"],
})

summary = pricing_experiment.groupby("variant", as_index=False).agg(
    total_users=("user_id", "count"),
    conversions=("converted", "sum"),
    total_revenue=("revenue", "sum"),
)
summary["conversion_rate"] = (summary["conversions"] / summary["total_users"]).round(4)
summary["revenue_per_visitor"] = (summary["total_revenue"] / summary["total_users"]).round(2)

control = summary[summary["variant"] == "Control"].iloc[0]
treatment = summary[summary["variant"] == "Treatment"].iloc[0]
absolute_uplift = treatment["conversion_rate"] - control["conversion_rate"]
relative_uplift = absolute_uplift / control["conversion_rate"] * 100

count = np.array([treatment["conversions"], control["conversions"]])
nobs = np.array([treatment["total_users"], control["total_users"]])
z_stat, p_value = proportions_ztest(count, nobs, alternative="larger")
ci_low, ci_high = confint_proportions_2indep(
    count1=treatment["conversions"],
    nobs1=treatment["total_users"],
    count2=control["conversions"],
    nobs2=control["total_users"],
    method="wald",
)

decision = "Roll out Treatment" if p_value < 0.05 and absolute_uplift > 0 else "Do not roll out yet"

print(summary)
print("Absolute Uplift:", round(absolute_uplift, 4))
print("Relative Uplift %:", round(relative_uplift, 2))
print("Z-Statistic:", round(z_stat, 4))
print("P-Value:", round(p_value, 4))
print("95% CI Lower:", round(ci_low, 4))
print("95% CI Upper:", round(ci_high, 4))
print("Decision:", decision)`,
      howItWorks: [
        'GroupBy creates experiment-level metrics for Control and Treatment.',
        'Conversion rate and revenue per visitor compare business outcomes.',
        'Absolute uplift measures direct conversion-rate improvement.',
        'Relative uplift measures improvement compared with Control.',
        'A two-proportion z-test checks whether Treatment is statistically better.',
        'The decision combines p-value, uplift direction, and business risk.',
      ],
      commonMistake: {
        title: 'Trusting Uplift Without Significance',
        points: [
          'Treatment has higher conversion and revenue per visitor in the sample.',
          'The sample is very small, so the business should consider p-value, confidence interval, and commercial risk before rollout.',
        ],
      } as { title: string; points: string[] } | undefined,
      observation: {
        title: 'Interview Insight',
        points: [
          'A strong analyst explains both statistical confidence and business impact.',
          'If the result is not statistically significant, continue the experiment with a larger sample.',
          'If significant, roll out gradually and monitor revenue, refunds, complaints, and acquisition quality.',
        ],
      } as { title: string; points: string[] } | undefined,
      result: [
        { variant: 'Control', total_users: '6', conversions: '2', total_revenue: '1998', conversion_rate: '0.3333', revenue_per_visitor: '333.00' },
        { variant: 'Treatment', total_users: '6', conversions: '4', total_revenue: '4796', conversion_rate: '0.6667', revenue_per_visitor: '799.33' },
      ] as Record<string, string>[],
    },
  },
};
