import type { FaqCategory } from "@/components/shared/CategoryFaq";

export const salesFaqCategories = [
  {
    id: "program",
    label: "Program & Audience",
    title: "Program & Audience FAQs",
    items: [
      ["Who is an AI for Sales training program designed for?", "The AI for Sales programme is designed for Sales teams, Sales Operations and MIS owners, commercial managers and business leaders responsible for recurring reporting, reconciliation, customer follow-up and sales-performance workflows."],
      ["What is AI for Sales training?", "AI for Sales training teaches sales teams how to apply Generative AI, Microsoft 365 tools, prompting, data workflows and AI agents to practical sales activities. The focus is on turning recurring Sales and MIS work into structured, refreshable workflows."],
      ["Do sales professionals need technical or programming knowledge to learn AI?", "No programming background is required for the core workshop. Participants learn through guided sales scenarios, approved or sanitized data, practical prompts, workflow designs and hands-on exercises."],
      ["Is AI for Sales training suitable for Sales Heads and business leaders?", "Yes. The programme can be configured for Sales Heads, commercial leaders and business managers who need visibility into sales performance, reporting efficiency, customer follow-up and AI adoption opportunities."],
      ["What are the benefits of AI training for sales teams?", "AI training can reduce repetitive reporting and data-preparation effort, accelerate payment and debtor analysis, improve exception identification, organize follow-up priorities and convert completed analysis into management-ready communication."],
      ["What sales functions can use AI?", "AI can support Sales Operations, MIS, account and customer management, collections-related follow-up, dealer management, performance reporting, product analysis, management reviews and recurring sales communication."],
    ],
  },
  {
    id: "use-cases",
    label: "Sales & MIS Use Cases",
    title: "AI Applications Across Sales & MIS",
    items: [
      ["How can AI be used in sales reporting?", "AI can help clean and structure ERP or sales data, calculate target-versus-achievement metrics, analyze dealer and product performance, identify exceptions and prepare management observations from approved reporting data."],
      ["Can AI automate Sales MIS reporting?", "Yes. AI can help create repeatable Sales MIS workflows from approved source files. These can cover data preparation, debtor reports, target-versus-achievement analysis, dealer and product summaries, exception lists and management communication."],
      ["Can AI help automate debtor reporting?", "Yes. The programme includes an automated debtor-reporting workflow that combines payment and ERP information, maps receipts to outstanding amounts, identifies overdue and unadjusted cases, assigns follow-up priority and creates management exception lists."],
      ["Can AI help with customer payment reconciliation?", "Yes. AI-assisted workflows can support customer-code mapping, identify fully or partially matched receipts, surface unadjusted payments and route ambiguous transactions for review."],
      ["Can AI automate bank statement preparation for sales teams?", "Yes. The programme covers bank-statement preparation, including cleaning and standardization, useful narration extraction, customer mapping and validation checks that can support a repeatable refresh process."],
      ["Can AI help identify overdue customers and collection priorities?", "Yes. AI can summarize outstanding positions, highlight ageing and high-value cases, identify payments received but not adjusted and apply approved business rules to organize follow-up priorities."],
      ["Can AI prioritize sales follow-up activities?", "Yes. A controlled workflow can apply approved rules to classify urgent follow-up, create customer-level action categories and draft internal comments. Commercial decisions and external customer communication remain subject to human review."],
      ["Can AI help with target versus achievement analysis?", "Yes. AI can calculate achievement percentages and variances, identify zero or below-target cases and prepare management observations around priority gaps."],
      ["Can AI analyze dealer performance?", "Yes. AI-assisted reporting can produce dealer-wise summaries, identify top and bottom performers, flag inactive or declining dealers and surface concentration indicators from approved data."],
      ["Can AI analyze product performance and product mix?", "Yes. AI can create product-wise summaries and dealer-product matrices, examine product mix and identify product-performance concerns for management review."],
      ["Can AI help sales teams create management reports and presentations?", "Yes. The programme includes a report-to-presentation workflow that converts completed analysis into an executive summary, a five-slide review structure, an action tracker and evidence-grounded management communication."],
      ["Can AI help create weekly sales review reports?", "Yes. A controlled Sales MIS workflow can read approved reports, answer recurring review questions, surface critical exceptions and prepare a consistent weekly management summary."],
      ["Can Microsoft Copilot be used by sales teams?", "Yes. The programme uses Microsoft 365 tools and can incorporate Copilot capabilities within the client's approved environment. Applications can include data analysis, reporting, communication and agent-based Sales MIS workflows."],
      ["Does the AI for Sales program include Copilot Agents?", "Yes. The programme includes Copilot Agent design for Sales and MIS workflows. Participants define knowledge sources, calculations, questions, outputs, controls, escalation rules and mandatory human approvals."],
      ["What can a Sales MIS Copilot Agent do?", "A Sales MIS Copilot Agent can work with approved debtor, dispatch, target, dealer or reporting data and answer recurring questions, surface exceptions and produce defined outputs according to the organization's reporting rules."],
      ["Can AI be used with ERP data for sales analysis?", "Yes. ERP data can be used where the organization's approved access and data-handling model permits it. The programme focuses on preparing clean reporting tables from ERP and other approved source files and then reusing those tables for multiple Sales reports."],
    ],
  },
  {
    id: "governance",
    label: "Systems & Governance",
    title: "Systems, Data & Governance",
    items: [
      ["Can AI integrate with our CRM or ERP?", "Integration depends on the organization's systems, permissions, connectors, data architecture and governance requirements. The workshop can demonstrate workflow designs using approved exports or available enterprise tools. Production integration requires separate testing, access controls and implementation work."],
      ["Does the workshop automate our entire Sales process?", "No. The workshop creates guided prototypes and repeatable workflow designs. Production automation requires stable inputs, integration, testing, monitoring, governance, ownership and appropriate approval controls."],
      ["How does the AI for Sales program protect customer and financial data?", "The programme uses approved or sanitized data, source-total validation and defined business rules. Customer mappings, financial adjustments, credit decisions, ownership assignments and external communication remain under human control."],
      ["How does the program prevent incorrect AI-generated sales reports?", "Workflows use source validation, explicit business rules, repeatable refresh logic, validation totals, exception handling and human review. AI-generated observations are separated from verified calculations and approved business actions."],
      ["Can AI be used safely for customer communication?", "Yes, with appropriate controls. AI can prepare internal or external communication drafts from approved information, while customer-facing messages and commercial decisions remain subject to responsible human review."],
      ["Can our Sales team use its own data during the training?", "Yes. Exercises can be configured around the organization's actual approved files or sanitized equivalents. Relevant source structures, customer codes, product hierarchies, ageing logic, targets, exception rules and reporting formats can be incorporated."],
      ["Can AI for Sales training be customized for our organization?", "Yes. Ivy Professional School configures the programme around the client's Sales and MIS process, ERP and bank-file structures, approved Microsoft 365 environment, customer and product hierarchies, validation requirements, management-reporting formats and human-approval boundaries."],
      ["Is the AI for Sales program hands-on or theoretical?", "The programme is hands-on. It includes guided work on bank statement preparation, reconciliation, debtor reporting, sales-performance reporting, management insights, Copilot Agent design and an integrated implementation exercise."],
    ],
  },
  {
    id: "delivery",
    label: "Delivery & Outcomes",
    title: "Customization, Delivery & Outcomes",
    items: [
      ["What will participants build during the AI for Sales program?", "Participants can build reusable Sales prompts, bank and reconciliation checklists, debtor-reporting workflows, target-versus-achievement analysis prompts, management-reporting templates, a Sales MIS Copilot Agent blueprint and a 30-day implementation plan."],
      ["How long is the AI for Sales training program?", "The flagship format is an 8-hour full-day workshop. It includes seven modules, three core cases and more than 12 Sales, MIS, action and reporting workflows."],
      ["What can a Sales team expect to achieve after AI training?", "The programme is designed to move teams from individual AI experimentation toward controlled, repeatable Sales and MIS workflows. Expected outputs include practical prototypes, reusable prompts and checklists, a Copilot Agent blueprint, defined controls and a 30-day implementation plan."],
      ["How can Sales leaders measure the ROI of AI adoption?", "Sales leaders can compare baseline and AI-assisted effort for recurring workflows, including data preparation, reconciliation, reporting, exception handling and management-pack creation. Useful measures include cycle time, refresh effort, exception visibility, adoption and pilot readiness."],
      ["What is the difference between AI for Sales training and generic AI training?", "Generic AI training focuses on broad AI concepts or general-purpose tools. AI for Sales training applies those capabilities to Sales and MIS workflows such as reconciliation, debtor reporting, target analysis, dealer performance, product analysis, follow-up prioritization and management reporting."],
      ["Is this AI for Sales program only about ChatGPT?", "No. The programme is designed around AI and Microsoft 365 tools, including Copilot and Copilot Agents where available in the client's approved environment. The focus is on workflow design and business application rather than a single AI tool."],
      ["What is agentic AI and why should sales teams understand it?", "Agentic AI refers to AI systems that can perform multi-step tasks, use tools and progress through defined workflows. For Sales and MIS teams, this can support recurring reporting, exception analysis, follow-up prioritization and management-review workflows with appropriate controls."],
      ["Can AI help Sales teams move from experimentation to implementation?", "Yes. The programme includes a 30-day implementation plan that documents a selected workflow, inputs, business rules, outputs, controls, owner, refresh frequency, expected benefit and immediate next action."],
      ["What industries can benefit from AI for Sales training?", "The programme can be adapted for manufacturing, consumer goods, distribution, infrastructure, technology, BFSI, healthcare, retail, professional services and other sectors with recurring Sales reporting, customer, dealer, payment or MIS workflows."],
      ["Can the training be delivered for an entire Sales and MIS team?", "Yes. The programme can be delivered to cross-functional Sales and MIS teams or organized into role-based tracks for Sales Operations, MIS, commercial teams, account teams and Sales leadership."],
      ["How does Ivy Professional School customize AI training for Sales teams?", "Ivy can assess Sales roles, Excel and Copilot comfort, current AI usage, recurring tasks, ERP and bank-file structures, reporting cadence, business rules, data readiness and approval requirements before configuring the curriculum, datasets, demonstrations and success measures."],
    ],
  },
] satisfies readonly FaqCategory[];
