import type { FaqCategory } from "@/components/shared/CategoryFaq";

export const financeFaqCategories = [
  {
    id: "program",
    label: "Program & Audience",
    title: "Program & Audience FAQs",
    items: [
      ["Who is an AI for Finance training program designed for?", "The AI for Finance program is designed for CFOs, finance heads, controllers, accountants, FP&A teams, Treasury, Tax, MIS and finance operations professionals who want to apply AI to analysis, reporting, reconciliation, controls and recurring finance workflows."],
      ["What is AI for Finance training?", "AI for Finance training teaches finance professionals how to apply Generative AI, Microsoft 365 Copilot, AI agents, Claude Skills and workflow automation to practical finance activities. The focus is on improving productivity while preserving finance controls, human review and auditability."],
      ["Do finance professionals need programming or technical knowledge to learn AI?", "No programming background is required for the core applied workshop. Participants learn through finance-specific prompts, datasets, workflows and guided exercises. The emphasis is on using AI safely and effectively within finance processes."],
      ["Is AI for Finance training suitable for CFOs and finance leaders?", "Yes. The programme can be configured for CFO and finance leadership teams as well as hands-on finance professionals. Leadership discussions can focus on AI opportunities, controls, business value, implementation priorities, governance and pilot selection."],
      ["What are the benefits of AI training for finance teams?", "AI training can help finance teams reduce repetitive analysis and reporting effort, accelerate reconciliation and exception investigation, improve recurring management reporting and identify controlled automation opportunities. The programme also teaches source verification, validation rules, maker-checker controls and audit trails."],
      ["What finance functions can use AI?", "AI can support Accounts Payable, Accounts Receivable, Treasury, Tax, Financial Reporting, MIS, FP&A, finance operations and governance. Typical workflows include reconciliation, invoice booking, payment allocation, receipt entry, tax reconciliation, interest validation, financial dashboards and SOP management."],
    ],
  },
  {
    id: "use-cases",
    label: "Finance Use Cases",
    title: "AI Applications Across Finance",
    items: [
      ["How can AI be used in financial analysis?", "AI can help structure financial analysis, investigate variances and exceptions, summarize findings and prepare management-ready narratives. Finance teams can use approved source data and defined calculation or validation rules to keep the analysis reviewable."],
      ["Can AI help automate financial reporting and MIS?", "Yes. AI can support recurring MIS preparation, variance analysis, financial commentary, dashboard interpretation and conversion of monthly reviews into management or CFO-ready presentation narratives."],
      ["Can Microsoft Copilot be used by finance teams?", "Yes. Microsoft 365 Copilot can support finance productivity in Excel, Outlook, Teams, Word and PowerPoint. The programme includes practical finance workflows such as analysing finance data, summarizing discussions, drafting control documents and preparing management narratives."],
      ["Does the AI for Finance program include Copilot Agents?", "Yes. The programme covers Copilot Projects and Agents and shows how controlled agents can support workflows such as AP exception analysis, SOP guidance, reconciliation investigation, MIS queries and tax knowledge."],
      ["Can Claude be used for finance and accounting workflows?", "Yes. Claude can be used to package repeatable finance logic into Skills and support approved analysis workflows. Ivy's programme includes Claude Skills, Plugins and a controlled Tally-to-AI workflow."],
      ["Can AI automate bank reconciliation?", "Yes. AI-assisted reconciliation can compare bank statements with ERP bank-book entries and surface charges, interest, duplicates, unidentified transactions and timing items for finance review."],
      ["Can AI automate ledger reconciliation?", "Yes. The programme covers one-to-one, one-to-many and partial settlement matching, classification of unmatched balances, variance reasoning and creation of an audit trail for review."],
      ["Can AI help with accounts payable and invoice processing?", "Yes. AI can extract invoice information, validate available PO and GRN information, identify potential duplicates and prepare controlled draft-entry support. Final accounting approval remains with authorised finance personnel."],
      ["Can AI help with vendor payment allocation?", "Yes. AI-assisted workflows can help allocate payments against invoices while accounting for deductions, advances, TDS, debit notes and partial settlements. Exceptions can be routed for finance review."],
      ["Can AI help with accounts receivable and receipt entry?", "Yes. AI can extract payment advice, match customer and invoice information, identify unapplied receipts and route exceptions such as LD cases for review."],
      ["Can AI be used for GST and GSTR-2B reconciliation?", "Yes. The programme covers GSTR-2B reconciliation using GSTIN, invoice values and tax components to identify missing invoices, duplicate claims and vendor compliance gaps for review."],
      ["Can AI help with Form 26AS reconciliation?", "Yes. AI-assisted workflows can match parties and PANs, validate sections and periods and prepare registers for missing credits or mismatches that require finance or tax review."],
      ["Can AI help validate loan interest charged by banks?", "Yes. The programme includes loan-interest validation using balances, rates and reset dates to calculate expected interest, compare charges and flag potential excess or penal interest for review."],
      ["Can AI support Schedule III mapping and financial reporting?", "Yes. AI can help map trial-balance accounts to a controlled disclosure hierarchy and surface classification or roll-forward exceptions for finance review."],
      ["Can AI help identify related-party transactions?", "Yes. Using approved entity and relationship masters, AI-assisted workflows can tag transactions and surface potentially unclassified related-party entities for review."],
      ["Can AI help create financial dashboards for CFOs?", "Yes. AI-assisted finance reporting can bring revenue, EBITDA, working capital, cash flow, borrowing, interest, variance and compliance exceptions into a management view. The programme also covers finance dashboards and management narratives."],
      ["Can AI help finance teams automate SOP reviews and reminders?", "Yes. AI can help review controlled SOPs, identify outdated or conflicting instructions and support ownership, version and review reminders. Governance and document ownership remain with the finance function."],
      ["How can AI be used in Treasury?", "AI can support bank reconciliation, cash and borrowing analysis, loan-interest validation, exception investigation and recurring Treasury reporting. Workflows should use approved source data and defined review controls."],
      ["How can AI be used in Tax and compliance?", "AI can assist with structured tax reconciliations, exception identification, document review, knowledge retrieval and compliance reporting. The programme specifically covers GSTR-2B, Form 26AS and controlled tax knowledge workflows."],
    ],
  },
  {
    id: "governance",
    label: "Controls & Data",
    title: "Governance, Controls & Data",
    items: [
      ["How does the AI for Finance program address financial data privacy?", "The programme emphasizes approved source data, controlled access, confidentiality, source verification and clear data boundaries. Finance, vendor, customer and tax information should remain within authorised enterprise environments and workflows."],
      ["How does the program prevent AI hallucinations and incorrect finance outputs?", "Finance workflows are designed around source grounding, explicit validation rules, calculation logic, tolerance criteria, missing-data checks and human review. AI-generated outputs are treated as reviewable work rather than final accounting decisions."],
      ["How does AI for Finance training address maker-checker controls?", "Maker-checker responsibilities are mapped into the workflow. AI can prepare analysis, matching, exception queues or draft support, while authorised finance personnel retain review and approval responsibility."],
      ["Can AI be connected directly to ERP or Tally?", "Yes, where the organization's approved systems and access model support it. The programme includes a read-only-first Cloud Tally-to-AI workflow and discusses approved exports or APIs. Any system write-back should pass through an explicit authorization gate."],
      ["Can our finance team use its own data and processes during the training?", "Yes. The programme can be configured around the client's finance operating model, ERP or Tally environment, reporting cycles, datasets, transaction types, policy rules and priority workflows. Sanitized or approved data should be used according to organizational policy."],
    ],
  },
  {
    id: "delivery",
    label: "Delivery & Outcomes",
    title: "Customization, Delivery & Outcomes",
    items: [
      ["Can AI for Finance training be customized for our organization?", "Yes. Ivy Professional School can configure the curriculum around finance functions, systems, data readiness, reporting templates, approval matrices, policy boundaries, priority use cases and desired success measures."],
      ["Is the AI for Finance program hands-on or theoretical?", "The programme is hands-on and structured around finance scenarios. Participants work through prompt design, Copilot workflows, agents and Skills, reconciliation, exception analysis and implementation planning."],
      ["What will finance participants build during the AI for Finance program?", "Participants can build a finance prompt library, Copilot Project and Agent blueprints, Claude Skills starter frameworks, reconciliation and exception toolkits, a finance automation playbook and a 30-day implementation action plan."],
      ["How long is the AI for Finance training program?", "The flagship format is an 8-hour applied workshop. The programme can also be extended into role-based labs, implementation sprints or a broader finance AI capability journey depending on organizational requirements."],
      ["What can a finance team expect to achieve after AI training?", "The programme is designed to move teams from individual AI experimentation toward controlled, repeatable finance workflows. Expected outputs include reusable finance assets, prioritized use cases, defined owners, controls, success KPIs and a 30-day action plan."],
      ["How can CFOs measure the ROI of AI adoption in finance?", "Finance leaders can compare baseline and AI-assisted cycle time, human review effort, rework, exception handling, reporting effort and process capacity. The programme uses measures such as cycle-time potential, exception traceability, pilot readiness and finance AI capability."],
      ["What is the difference between AI for Finance training and generic AI training?", "Generic AI training focuses on broad AI concepts or general-purpose tools. AI for Finance training applies AI to finance workflows such as reconciliation, reporting, AP, AR, Treasury, Tax, controls and MIS while incorporating finance-specific validation, approval and audit requirements."],
      ["Is this AI for Finance program only about ChatGPT?", "No. The programme covers Microsoft 365 Copilot, Copilot Projects and Agents, Claude Skills and Plugins, Tally workflows and governed finance automation. The emphasis is on selecting appropriate capabilities for specific finance workflows."],
      ["What is agentic AI and why should finance teams understand it?", "Agentic AI refers to AI systems that can perform multi-step tasks, use tools and progress through defined workflows. Finance teams can apply this approach to exception analysis, reconciliation investigation, SOP guidance, MIS queries and other repeatable workflows with appropriate approval controls."],
      ["Can AI help finance teams move from experimentation to implementation?", "Yes. The programme includes an implementation roadmap that defines the workflow, inputs, outputs, controls, owner, KPI and next 30-day action. Candidate workflows can then be prioritized for controlled pilots."],
      ["What industries can benefit from AI for Finance training?", "The programme can be adapted for manufacturing, BFSI, healthcare, technology, consulting, retail, education, infrastructure, professional services and other sectors with recurring finance, reporting, reconciliation and compliance workflows."],
      ["Can the training be delivered for an entire finance team?", "Yes. The programme can be delivered to cross-functional finance teams or through role-based tracks for Accounts, Treasury, Tax, MIS, FP&A and CFO-office teams."],
      ["How does Ivy Professional School customize AI training for finance teams?", "Ivy can assess finance roles, current AI usage, approved tools, ERP or Tally access, data readiness, reporting cycles, controls and priority workflows before configuring the programme. The curriculum, datasets, exercises, outputs and KPIs can then be aligned to the organization's requirements."],
    ],
  },
] satisfies readonly FaqCategory[];
