import UseCaseCards from "../ai-for-leaders-and-cxos/UseCaseCards";
import Image from "next/image";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import { ArrowRight, Check, ShieldCheck, Sparkles } from "lucide-react";
import styles from "../ai-for-leaders-and-cxos/leaders.module.css";
import ProgramGallery from "../ai-for-leaders-and-cxos/ProgramGallery";
import aiLeaders1 from "@/assests/aileaders1.jpeg";
import aiLeaders2 from "@/assests/aileaders2.jpeg";
import aiLeaders3 from "@/assests/aileaders3.jpeg";
import aiLeaders4 from "@/assests/aileaders4.jpeg";
import aiLeaders5 from "@/assests/aileaders5.jpeg";
import cxo1 from "@/assests/cxo1.jpeg";
import cxo2 from "@/assests/cxo2.jpeg";
import cxo3 from "@/assests/cxo3.jpeg";
import cxo4 from "@/assests/cxo4.jpeg";
import cxo5 from "@/assests/cxo5.jpeg";
import cxo6 from "@/assests/cxo6.jpeg";
import aiHr from "@/assests/aihr.jpeg";
import atlasCopcoLogo from "@/assests/Atlas Copco Logotype for white BG_CMYK.png";
import bcclLogo from "@/assests/BCCL - Times of India.webp";
import canonLogo from "@/assests/Canon.png";
import bridgestoneLogo from "@/assests/Bridgestone.png";
import capgeminiLogo from "@/assests/Capgemini-Logo.png";
import genpactLogo from "@/assests/Genpact Logo.png";
import tataSteelLogo from "@/assests/Tata Steel.png";
import itcLogo from "@/assests/ITC.png";
import honeywellLogo from "@/assests/Honeywell.png";
import mspSteelLogo from "@/assests/MSP Steel.png";

const modules = [
  ["01 · 30 MIN", "AI for Finance and Responsible Use", "Build a common foundation across AI, GenAI, agents, Skills and Plugins. Classify tasks by risk and define data, review and approval boundaries.", "FOUNDATION"],
  ["02 · 45 MIN", "Prompt Engineering for Finance", "Use RICF to create reusable prompts with accounting rules, calculation logic, tolerances, output formats, missing-data checks and validation instructions.", "HANDS-ON"],
  ["03 · 60 MIN", "Microsoft 365 Copilot for Finance Productivity", "Analyse finance data in Excel, summarize Teams and Outlook content, draft control documents and convert monthly reviews into CFO-ready presentation narratives.", "HANDS-ON"],
  ["04 · 60 MIN", "Copilot Projects and Finance Agents", "Create recurring finance workspaces and design controlled agents for AP exceptions, SOP guidance, reconciliation investigation, MIS queries and tax knowledge.", "BLUEPRINT BUILD"],
  ["05 · 60 MIN", "Claude Skills, Plugins and Cloud Tally", "Package repeatable finance logic into Skills, connect approved enterprise sources and map a read-only-first Tally-to-AI workflow.", "GUIDED BUILD"],
  ["06 · 90 MIN", "Reconciliation, Treasury and Control Automation", "Apply structured matching and exception analysis to ledger, bank, GSTR-2B, Form 26AS and loan-interest validation workflows.", "INTENSIVE LAB"],
  ["07 · 45 MIN", "Transaction, Reporting and Compliance Automation", "Map invoice booking, payment allocation, receipt entry, Schedule III mapping, RPT tagging, dashboards and SOP governance.", "GUIDED EXERCISE"],
  ["08 · 30 MIN", "Finance AI Implementation Roadmap", "Select one workflow per function and define inputs, output, controls, owner, KPI and the next 30-day action.", "GROUP ACTIVITY"],
] as const;
const cases = [
  ["FINANCE & ACCOUNTS", "Ledger Reconciliation", "Match one-to-one, one-to-many and partial settlements; classify unmatched balances; prepare variance reasons and an audit trail."],
  ["TREASURY", "Bank Reconciliation", "Match bank statements with ERP bank-book entries and detect charges, interest, duplicates, unidentified transactions and timing items."],
  ["ACCOUNTS PAYABLE", "Purchase Invoice Booking", "Extract invoice data, validate PO and GRN records, identify duplicates and prepare controlled draft-entry support."],
  ["ACCOUNTS PAYABLE", "Vendor Payment Allocation", "Allocate bill-to-bill payments across invoices, deductions, advances, TDS, debit notes and partial settlements."],
  ["ACCOUNTS RECEIVABLE", "Receipt Entry from Advice", "Extract payment advice, match customer and invoice records, route LD cases and produce an unapplied receipt report."],
  ["INDIRECT TAX", "GSTR-2B Reconciliation", "Compare GSTIN, invoice values and tax components to identify missing invoices, duplicate claims and vendor compliance gaps."],
  ["DIRECT TAX", "Form 26AS Reconciliation", "Match parties and PANs, validate sections and periods, and prepare missing-credit and mismatch follow-up registers."],
  ["TREASURY", "Loan Interest Validation", "Calculate expected interest from balances, rates and reset dates; compare bank charges and flag excess or penal interest."],
  ["FINANCIAL REPORTING", "Schedule III Mapping", "Map trial-balance accounts to a controlled disclosure hierarchy and surface classification and roll-forward exceptions."],
  ["COMPLIANCE", "Related-Party Tagging", "Use approved masters and entity relationships to tag transactions and surface unclassified-entity alerts."],
  ["CFO OFFICE / MIS", "Financial Dashboards", "Bring revenue, EBITDA, working capital, cash flow, borrowing, interest, variance and compliance exceptions into one view."],
  ["GOVERNANCE", "SOP Review and Reminders", "Manage controlled SOPs, review outdated or conflicting instructions and automate ownership, version and review reminders."],
] as const;
const delivery = [
  ["BEFORE", "Assess and configure", ["Sponsor and process-owner discovery", "Finance workflow and control mapping", "Tool and system readiness review", "Sanitized dataset preparation", "Use-case and KPI selection"]],
  ["DURING", "Practise and build", ["Finance-specific prompt design", "Copilot productivity workflows", "Agent and Skill blueprints", "Reconciliation case lab", "Validation and approval design"]],
  ["AFTER", "Activate and measure", ["Finance prompt and template pack", "Prioritized automation playbook", "Use-case owners and success KPIs", "30-day action plan", "Pilot shortlist and governance review"]],
] as const;
const metrics = [
  ["20–30%", "TARGET KNOWLEDGE UPLIFT", "Finance AI capability", "Improvement in structured prompting, responsible-use decisions, workflow design and finance validation practices.", "MEASURE: PRE/POST SCORE"],
  ["≥80%", "TARGET LAB COMPLETION", "Applied skill", "Participants complete the assigned prompt, reconciliation, Project, Agent or Skill activity to the required standard.", "MEASURE: TASK RUBRIC"],
  ["100%", "OF SHORTLISTED USE CASES SCORED", "Opportunity quality", "Each candidate is assessed for business value, feasibility, data readiness, risk, controls and ownership.", "MEASURE: USE-CASE SCORECARD"],
  ["15–30%", "TARGET CYCLE-TIME POTENTIAL", "Process productivity", "Estimated reduction for selected recurring finance tasks, validated through a controlled pilot before scale.", "MEASURE: TIME PER CYCLE"],
  ["≥90%", "TARGET EXCEPTION TRACEABILITY", "Review quality", "Matched and unmatched records retain a clear reason, source reference, reviewer status and next action.", "MEASURE: EXCEPTION AUDIT"],
  ["3–5", "PILOT-READY WORKFLOWS", "Implementation readiness", "Shortlisted opportunities have defined inputs, output, owner, controls, data access and success criteria.", "MEASURE: PILOT READINESS"],
] as const;
const takeaways = [["Finance prompt library", "Reusable templates for reconciliation, variance review, reporting and communication."], ["Copilot Project and Agent blueprint", "Defined knowledge sources, instructions, outputs, approvals and escalation rules."], ["Claude Skills starter framework", "Repeatable logic for ledger, bank, tax, mapping and MIS workflows."], ["Reconciliation and exception toolkit", "Structured matching, investigation and audit-ready output patterns."], ["Finance automation playbook", "A mapped portfolio with inputs, outputs, controls, owners and implementation waves."], ["30-day action plan", "A selected workflow, success KPI and accountable next step for each function."]] as const;
const programPhotos = [aiLeaders1, aiLeaders2, aiLeaders3, aiLeaders4, aiLeaders5, cxo1, cxo2, cxo3, cxo4, cxo5, cxo6].map((src, index) => ({src, alt: "Enterprise teams collaborating in a practical AI workshop — program highlight " + (index + 1)}));
programPhotos.push({src: aiHr, alt: "Group photograph of participants at an Ivy enterprise AI program"});
const clientLogos = [{src: atlasCopcoLogo, name: "Atlas Copco"}, {src: bcclLogo, name: "BCCL – The Times of India"}, {src: canonLogo, name: "Canon"}, {src: bridgestoneLogo, name: "Bridgestone"}, {src: capgeminiLogo, name: "Capgemini"}, {src: genpactLogo, name: "Genpact"}, {src: tataSteelLogo, name: "Tata Steel"}, {src: itcLogo, name: "ITC"}, {src: honeywellLogo, name: "Honeywell"}, {src: mspSteelLogo, name: "MSP Steel"}];

export default function FinancePage() {
  return <div className={styles.page}><Navbar/><main>
    <section className={styles.hero} id="top"><div className={styles.shell + " " + styles.heroGrid}><div><p className={styles.eyebrow}>ENTERPRISE AI CAPABILITY PROGRAM</p><h1>AI for <span>Finance</span></h1><p className={styles.heroLead}>Help finance teams improve productivity, reconciliation, reporting and control through applied Microsoft 365 Copilot, Copilot Agents, Claude Skills and governed finance automation.</p><div className={styles.actions}><a className={styles.button} href="#outline">Explore the program <ArrowRight size={17}/></a><a href="#cases">View finance use cases</a></div><div className={styles.trust}><span><Check/> 8-hour applied workshop</span><span><Check/> Read-only-first automation</span><span><Check/> Human approval built in</span></div></div><aside className={styles.heroPanel}><div className={styles.panelTop}><span>FINANCE WORKSHOP</span><span>LIVE + HANDS-ON</span></div><div className={styles.panelCore}><p>From finance task to controlled workflow</p>{[["01", "Structure", "Prompts and source data"], ["02", "Analyse", "Variances and exceptions"], ["03", "Reconcile", "Ledger, bank and tax"], ["04", "Automate", "Projects, agents and skills"]].map(item => <div className={styles.journey} key={item[0]}><strong>{item[0]}</strong><b>{item[1]}</b><small>{item[2]}</small></div>)}<div className={styles.result}><Sparkles/><p>Participants leave with reusable finance assets, a prioritized use-case playbook and a 30-day action plan.</p></div></div></aside></div></section>
    <section className={styles.proof}><div className={styles.shell + " " + styles.proofGrid}>{[["8 hours", "Applied workshop format"], ["15", "Mapped finance use cases"], ["8", "Quick-win opportunities"], ["30 days", "Implementation action plan"]].map(item => <div key={item[0]}><strong>{item[0]}</strong><span>{item[1]}</span></div>)}</div></section>
    <section className={styles.photoSection} id="program-photos"><div className={styles.photoGlow}/><div className={styles.shell}><div className={styles.photoIntro}><div><p className={styles.eyebrow}>PROGRAMS IN ACTION</p><h2>Show finance teams working through <span>real scenarios.</span></h2></div><div className={styles.photoSummary}><p>Add approved photographs from prior AI for Finance, finance automation, Copilot or related enterprise programs delivered by Ivy Professional School.</p></div></div><ProgramGallery photos={programPhotos}/></div></section>
    <section className={styles.section}><div className={styles.shell + " " + styles.twoCol}><div><p className={styles.eyebrow}>PROGRAM PURPOSE</p><h2>Finance work moves from manual effort to reviewable intelligence.</h2></div><div className={styles.leadCopy}><p>The program connects everyday finance productivity with reconciliation, treasury, taxation, reporting and transaction workflows. Teams learn how to structure source-grounded AI tasks, investigate exceptions, design repeatable agents and preserve maker-checker controls, audit trails and finance ownership.</p></div></div></section>
    <section className={styles.section}><div className={styles.shell}><div className={styles.diagnosticHead}><p className={styles.eyebrow}>CONFIGURED FOR YOUR FINANCE FUNCTION</p><h2>We start with workflows, controls and available systems.</h2><p>The workshop is configured around the client’s finance operating model, approved tools, data access, ERP or Tally environment, recurring reporting cycles and policy boundaries.</p></div><div className={styles.diagnostic}>{[["Process discovery", "Identify high-effort finance tasks, recurring exceptions, close-cycle pressure and reporting bottlenecks."], ["Data readiness", "Review file structures, masters, identifiers, reference quality and access to approved source data."], ["Control mapping", "Define maker-checker responsibilities, tolerance rules, approval gates and audit expectations."], ["Curriculum design", "Select datasets, demonstrations and exercises relevant to Accounts, Treasury, Tax, MIS and CFO teams."], ["Outcome baseline", "Agree learning, adoption, cycle-time, exception-quality and pilot-readiness measures."]].map((item, index) => <article key={item[0]}><b>0{index + 1}</b><h3>{item[0]}</h3><p>{item[1]}</p></article>)}</div><div className={styles.configNote}><article><h3>What changes by client</h3><p>ERP and finance systems, chart of accounts, transaction types, policy rules, tax processes, reporting templates, approval matrix, datasets and selected use cases.</p></article><article><h3>What remains consistent</h3><p>Source verification, human review, confidentiality, auditability, controlled access, exception handling and clear implementation ownership.</p></article></div></div></section>
    <section className={styles.section} id="outline"><div className={styles.shell}><div className={styles.heading}><div><p className={styles.eyebrow}>FLAGSHIP OUTLINE</p><h2>Eight modules.<br/>One applied finance journey.</h2></div><p>The full-day format combines finance-specific prompting, Microsoft 365 Copilot, Copilot Projects and Agents, Claude Skills, Tally integration, reconciliation labs and implementation planning.</p></div><div className={styles.modules}>{modules.map(m => <article key={m[0]}><span>{m[0]}</span><div><h3>{m[1]}</h3><p>{m[2]}</p></div><b>{m[3]}</b></article>)}</div></div></section>
    <section className={styles.dark} id="cases"><div className={styles.shell + " " + styles.section + " " + styles.casesShell}><div className={styles.heading}><div><p className={styles.eyebrow}>FINANCE AUTOMATION PORTFOLIO</p><h2>Real finance processes become the learning material.</h2></div><p>The use-case library is based on the supplied Finance Automation Use Case Register. Each workflow includes the business problem, required inputs, proposed automation, expected outputs and approval controls.</p></div><UseCaseCards cases={cases}/><div className={styles.configNote}><article><p className={styles.eyebrow}>FEATURED RECONCILIATION LAB</p><h3>From raw transactions to an audit-ready exception queue</h3><p>Participants standardize source files, apply deterministic and fuzzy matching logic, investigate exceptions and produce a concise management summary.</p><p><strong>Prepare → Match → Classify → Investigate → Review</strong></p></article><article><p className={styles.eyebrow}>FEATURED INTEGRATION LAB</p><h3>Controlled Cloud Tally-to-AI workflow</h3><p>Teams design a governed path from approved Tally exports or APIs to Claude Skills or Copilot analysis, keeping finance approval before any posting or write-back.</p><p><strong>Extract → Analyse → Reconcile → Finance review → Approved action</strong></p></article></div></div></section>
    <section className={styles.economics}><div className={styles.shell + " " + styles.economicsGrid}><div><p className={styles.eyebrow}>FINANCE CONTROL ARCHITECTURE</p><h2>Every automation is designed for review.</h2></div><div><p className={styles.leadCopy}>Participants learn how to keep AI outputs traceable, bounded and suitable for finance use. The program begins with analysis and reconciliation before any system action is considered.</p><div className={styles.costGrid}>{[["SOURCE GROUNDING", "Use approved ledgers, statements, policies, masters and reference files."], ["VALIDATION RULES", "Specify tolerances, accounting logic, completeness checks and exception criteria."], ["MAKER-CHECKER", "Separate preparation, review and final approval responsibilities."], ["AUDIT TRAIL", "Retain matched records, unmatched items, reasons, evidence and reviewer action."], ["ACCESS CONTROL", "Protect financial, vendor, customer, tax and payroll information."], ["WRITE-BACK GATE", "Require explicit authorization before draft entries, posting or system updates."]].map(item => <div key={item[0]}><strong>{item[0]}</strong><span>{item[1]}</span></div>)}</div></div></div></section>
    <section className={styles.section}><div className={styles.shell}><div className={styles.heading}><div><p className={styles.eyebrow}>HOW WE DELIVER</p><h2>Assess. Configure. Practise. Activate.</h2></div><p>The workshop connects capability building with practical finance implementation. Approved data, control ownership and measurable outcomes are designed in from the start.</p></div><div className={styles.delivery}>{delivery.map(item => <article key={item[0]}><span>{item[0]}</span><h3>{item[1]}</h3><ul>{item[2].map(point => <li key={point}>{point}</li>)}</ul></article>)}</div></div></section>
    <section className={styles.outcomes} id="outcomes"><div className={styles.shell + " " + styles.section}><div className={styles.heading}><div><p className={styles.eyebrow}>OUTCOMES AND IMPACT METRICS</p><h2>Measures a finance sponsor can track.</h2></div><div><p className={styles.eyebrow}>ILLUSTRATIVE TARGET FRAMEWORK</p><p>Final targets should be set after baseline assessment and adjusted for process volume, data quality, system access and selected workflows.</p></div></div><div className={styles.metricGrid}>{metrics.map(item => <article key={item[2]}><strong>{item[0]}</strong><small>{item[1]}</small><h3>{item[2]}</h3><p>{item[3]}</p><span>{item[4]}</span></article>)}<div className={styles.note}><ShieldCheck/> <span><strong>Measurement principle:</strong> these figures are proposed program targets. Actual baselines, targets and achieved results should be agreed and reported for each client engagement.</span></div></div></div></section>
    <section className={styles.logoSection}><div className={styles.shell}><div className={styles.logoHead}><div><h2>Trusted for enterprise capability building</h2></div><p>Add approved logos from clients for whom Ivy has delivered AI, analytics, finance, Copilot or automation programs.</p></div></div><div className={styles.logoCarousel}><div className={styles.logoTrack}>{[...clientLogos, ...clientLogos].map((client, index) => <div className={styles.logoItem} key={client.name + index} aria-hidden={index >= clientLogos.length}><Image src={client.src} alt={index < clientLogos.length ? client.name + " logo" : ""} sizes="180px"/></div>)}</div></div></section>
    <section className={styles.linkedinSection} id="linkedin-posts"><div className={styles.shell + " " + styles.section}><div className={styles.heading}><div><p className={styles.eyebrow}>CLIENTS MENTIONING IVY</p><h2>See the programs through our clients&apos; LinkedIn posts.</h2></div><p>Explore the professionals and client organizations connected with Ivy Professional School&apos;s leadership programs.</p></div><div className={styles.linkedinGrid}>{[{name:"Preeti N Shah",company:"Bennett Coleman & Co. Ltd.",quote:"A big thank you to Prateek Agrawal for making the sessions so fun, practical, thought-provoking & easy to connect with real-world HR challenges.",postUrl:"https://lnkd.in/p/dD-u32YW"},{name:"Kanchan Bose",company:"MSP Steel",quote:"A big thank you to Mr. Prateek Agrawal for delivering highly practical sessions focused on real business applications of AI. It was great to explore how AI can enhance productivity, automate routine tasks, and support better decision-making.",postUrl:"https://www.linkedin.com/posts/kanchan88_%F0%9D%90%80%F0%9D%90%88-%F0%9D%90%A2%F0%9D%90%AC-%F0%9D%90%82%F0%9D%90%A1%F0%9D%90%9A%F0%9D%90%A7%F0%9D%90%A0%F0%9D%90%A2%F0%9D%90%A7%F0%9D%90%A0-%F0%9D%90%96%F0%9D%90%A8%F0%9D%90%AB%F0%9D%90%A4-%F0%9D%90%8B%F0%9D%90%9E-activity-7484436858446344192-KiVa"},{name:"Devanganaa Sharma",company:"Bennett Coleman & Co. Ltd.",quote:"The AI for HR workshop was less about learning another tool and more about understanding what’s becoming possible. A special thanks to Prateek Agrawal for spending these two days with us and generously sharing his knowledge, perspectives and some serious AI wisdom!",postUrl:"https://lnkd.in/p/dXZZbJfb"}].map(item => <article className={styles.linkedinSlot} key={item.postUrl}><h3>{item.name}</h3><p className={styles.clientCompany}>{item.company}</p><blockquote><span className={styles.quoteMark}>“</span>{item.quote}</blockquote><a className={styles.linkPlaceholder} href={item.postUrl} target="_blank" rel="noopener noreferrer">VIEW LINKEDIN POST →</a></article>)}</div></div></section>
    <section className={styles.takeaways}><div className={styles.shell + " " + styles.twoCol}><div><p className={styles.eyebrow}>WHAT PARTICIPANTS TAKE BACK</p><h2>A finance toolkit ready for recurring work.</h2></div><div>{takeaways.map((item, index) => <p key={item[0]}><b>{String(index + 1).padStart(2, "0")}</b><span><strong>{item[0]}</strong>{item[1]}</span></p>)}</div></div></section>
    <section className={styles.roadmap}><div className={styles.shell + " " + styles.roadmapGrid}><div><p className={styles.eyebrow}>FROM WORKSHOP TO SCALE</p><h2>A phased finance journey</h2></div>{[["PHASE 1", "Quick wins", "Read-only analysis, reconciliation, prompt libraries and recurring reporting support."], ["PHASE 2", "Controlled workflows", "Projects, agents, Skills, document intake, approvals and exception routing."], ["PHASE 3", "Integrated automation", "Governed ERP or Tally connectivity, monitored performance and approved write-back."]].map(item => <article key={item[0]}><span>{item[0]}</span><h3>{item[1]}</h3><p>{item[2]}</p></article>)}</div></section>
    <section className={styles.proof}><div className={styles.shell + " " + styles.proofGrid}><div><strong>Enterprise capability building by Ivy Professional School</strong></div><div><strong>18+</strong><span>Years in education</span></div><div><strong>37,500+</strong><span>Learners and alumni</span></div><div><strong>400+</strong><span>Educators</span></div><div><strong>300+</strong><span>Corporate recruiters</span></div></div></section>
    <section className={styles.cta}><div className={styles.shell}><p className={styles.eyebrow}>DESIGN YOUR PROGRAM</p><h2>Bring your finance priorities.<br/>We will build the learning around them.</h2><p>Share your finance functions, approved AI stack, systems, reporting cycles and priority workflows.</p><a className={styles.button} href="mailto:corporate@ivyproschool.com">Discuss your AI for Finance program <ArrowRight size={17}/></a></div></section>
  </main><Footer/></div>;
}
