import UseCaseCards from "../ai-for-leaders-and-cxos/UseCaseCards";
import Image from "next/image";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import { ArrowRight, Check, ShieldCheck, Sparkles } from "lucide-react";
import styles from "../ai-for-leaders-and-cxos/leaders.module.css";
import ProgramGallery from "../ai-for-leaders-and-cxos/ProgramGallery";
import aiLeaders1 from "@/assests/aileaders1.jpeg";
import aiLeaders2 from "@/assests/aileaders2.jpeg";
import aiLeaders3 from "@/assests/aileaders3.jpeg";
import aiLeaders4 from "@/assests/aileaders4.jpeg";
import aiLeaders5 from "@/assests/aileaders5.jpeg";
import cxo1 from "@/assests/cxo1.jpeg";
import cxo2 from "@/assests/cxo2.jpeg";
import cxo3 from "@/assests/cxo3.jpeg";
import cxo4 from "@/assests/cxo4.jpeg";
import cxo5 from "@/assests/cxo5.jpeg";
import cxo6 from "@/assests/cxo6.jpeg";
import aiHr from "@/assests/aihr.jpeg";
import atlasCopcoLogo from "@/assests/Atlas Copco Logotype for white BG_CMYK.png";
import bcclLogo from "@/assests/BCCL - Times of India.webp";
import canonLogo from "@/assests/Canon.png";
import bridgestoneLogo from "@/assests/Bridgestone.png";
import capgeminiLogo from "@/assests/Capgemini-Logo.png";
import genpactLogo from "@/assests/Genpact Logo.png";
import tataSteelLogo from "@/assests/Tata Steel.png";
import itcLogo from "@/assests/ITC.png";
import honeywellLogo from "@/assests/Honeywell.png";
import mspSteelLogo from "@/assests/MSP Steel.png";

const modules = [
  ["01 · 30 MIN", "AI for Finance and Responsible Use", "Build a common foundation across AI, GenAI, agents, Skills and Plugins. Classify tasks by risk and define data, review and approval boundaries.", "FOUNDATION"],
  ["02 · 45 MIN", "Prompt Engineering for Finance", "Use RICF to create reusable prompts with accounting rules, calculation logic, tolerances, output formats, missing-data checks and validation instructions.", "HANDS-ON"],
  ["03 · 60 MIN", "Microsoft 365 Copilot for Finance Productivity", "Analyse finance data in Excel, summarize Teams and Outlook content, draft control documents and convert monthly reviews into CFO-ready presentation narratives.", "HANDS-ON"],
  ["04 · 60 MIN", "Copilot Projects and Finance Agents", "Create recurring finance workspaces and design controlled agents for AP exceptions, SOP guidance, reconciliation investigation, MIS queries and tax knowledge.", "BLUEPRINT BUILD"],
  ["05 · 60 MIN", "Claude Skills, Plugins and Cloud Tally", "Package repeatable finance logic into Skills, connect approved enterprise sources and map a read-only-first Tally-to-AI workflow.", "GUIDED BUILD"],
  ["06 · 90 MIN", "Reconciliation, Treasury and Control Automation", "Apply structured matching and exception analysis to ledger, bank, GSTR-2B, Form 26AS and loan-interest validation workflows.", "INTENSIVE LAB"],
  ["07 · 45 MIN", "Transaction, Reporting and Compliance Automation", "Map invoice booking, payment allocation, receipt entry, Schedule III mapping, RPT tagging, dashboards and SOP governance.", "GUIDED EXERCISE"],
  ["08 · 30 MIN", "Finance AI Implementation Roadmap", "Select one workflow per function and define inputs, output, controls, owner, KPI and the next 30-day action.", "GROUP ACTIVITY"],
] as const;

const cases = [
  ["FINANCE & ACCOUNTS", "Ledger Reconciliation", "Match one-to-one, one-to-many and partial settlements; classify unmatched balances; prepare variance reasons and an audit trail."],
  ["TREASURY", "Bank Reconciliation", "Match bank statements with ERP bank-book entries and detect charges, interest, duplicates, unidentified transactions and timing items."],
  ["ACCOUNTS PAYABLE", "Purchase Invoice Booking", "Extract invoice data, validate PO and GRN records, identify duplicates and prepare controlled draft-entry support."],
  ["ACCOUNTS PAYABLE", "Vendor Payment Allocation", "Allocate bill-to-bill payments across invoices, deductions, advances, TDS, debit notes and partial settlements."],
  ["ACCOUNTS RECEIVABLE", "Receipt Entry from Advice", "Extract payment advice, match customer and invoice records, route LD cases and produce an unapplied receipt report."],
  ["INDIRECT TAX", "GSTR-2B Reconciliation", "Compare GSTIN, invoice values and tax components to identify missing invoices, duplicate claims and vendor compliance gaps."],
  ["DIRECT TAX", "Form 26AS Reconciliation", "Match parties and PANs, validate sections and periods, and prepare missing-credit and mismatch follow-up registers."],
  ["TREASURY", "Loan Interest Validation", "Calculate expected interest from balances, rates and reset dates; compare bank charges and flag excess or penal interest."],
  ["FINANCIAL REPORTING", "Schedule III Mapping", "Map trial-balance accounts to a controlled disclosure hierarchy and surface classification and roll-forward exceptions."],
  ["COMPLIANCE", "Related-Party Tagging", "Use approved masters and entity relationships to tag transactions and surface unclassified-entity alerts."],
  ["CFO OFFICE / MIS", "Financial Dashboards", "Bring revenue, EBITDA, working capital, cash flow, borrowing, interest, variance and compliance exceptions into one view."],
  ["GOVERNANCE", "SOP Review and Reminders", "Manage controlled SOPs, review outdated or conflicting instructions and automate ownership, version and review reminders."],
] as const;

const delivery = [
  ["BEFORE", "Assess and configure", ["Sponsor and process-owner discovery", "Finance workflow and control mapping", "Tool and system readiness review", "Sanitized dataset preparation", "Use-case and KPI selection"]],
  ["DURING", "Practise and build", ["Finance-specific prompt design", "Copilot productivity workflows", "Agent and Skill blueprints", "Reconciliation case lab", "Validation and approval design"]],
  ["AFTER", "Activate and measure", ["Finance prompt and template pack", "Prioritized automation playbook", "Use-case owners and success KPIs", "30-day action plan", "Pilot shortlist and governance review"]],
] as const;

const metrics = [
  ["20–30%", "TARGET KNOWLEDGE UPLIFT", "Finance AI capability", "Improvement in structured prompting, responsible-use decisions, workflow design and finance validation practices.", "MEASURE: PRE/POST SCORE"],
  ["≥80%", "TARGET LAB COMPLETION", "Applied skill", "Participants complete the assigned prompt, reconciliation, Project, Agent or Skill activity to the required standard.", "MEASURE: TASK RUBRIC"],
  ["100%", "OF SHORTLISTED USE CASES SCORED", "Opportunity quality", "Each candidate is assessed for business value, feasibility, data readiness, risk, controls and ownership.", "MEASURE: USE-CASE SCORECARD"],
  ["15–30%", "TARGET CYCLE-TIME POTENTIAL", "Process productivity", "Estimated reduction for selected recurring finance tasks, validated through a controlled pilot before scale.", "MEASURE: TIME PER CYCLE"],
  ["≥90%", "TARGET EXCEPTION TRACEABILITY", "Review quality", "Matched and unmatched records retain a clear reason, source reference, reviewer status and next action.", "MEASURE: EXCEPTION AUDIT"],
  ["3–5", "PILOT-READY WORKFLOWS", "Implementation readiness", "Shortlisted opportunities have defined inputs, output, owner, controls, data access and success criteria.", "MEASURE: PILOT READINESS"],
] as const;

const takeaways = [
  ["Finance prompt library", "Reusable templates for reconciliation, variance review, reporting and communication."],
  ["Copilot Project and Agent blueprint", "Defined knowledge sources, instructions, outputs, approvals and escalation rules."],
  ["Claude Skills starter framework", "Repeatable logic for ledger, bank, tax, mapping and MIS workflows."],
  ["Reconciliation and exception toolkit", "Structured matching, investigation and audit-ready output patterns."],
  ["Finance automation playbook", "A mapped portfolio with inputs, outputs, controls, owners and implementation waves."],
  ["30-day action plan", "A selected workflow, success KPI and accountable next step for each function."],
] as const;

const programPhotos = [aiLeaders1, aiLeaders2, aiLeaders3, aiLeaders4, aiLeaders5, cxo1, cxo2, cxo3, cxo4, cxo5, cxo6].map((src, index) => ({ src, alt: `Enterprise teams collaborating in a practical AI workshop — program highlight ${index + 1}` }));
programPhotos.push({ src: aiHr, alt: "Group photograph of participants at an Ivy enterprise AI program" });
const clientLogos = [{src: atlasCopcoLogo, name: "Atlas Copco"}, {src: bcclLogo, name: "BCCL – The Times of India"}, {src: canonLogo, name: "Canon"}, {src: bridgestoneLogo, name: "Bridgestone"}, {src: capgeminiLogo, name: "Capgemini"}, {src: genpactLogo, name: "Genpact"}, {src: tataSteelLogo, name: "Tata Steel"}, {src: itcLogo, name: "ITC"}, {src: honeywellLogo, name: "Honeywell"}, {src: mspSteelLogo, name: "MSP Steel"}];
const faqs = [
  ["Who is this AI for Finance program designed for?", "The program is designed for CFO-office, finance and accounts, treasury, AP, AR, tax, compliance, MIS and transformation teams working on recurring finance workflows."],
  ["Which tools are used during the program?", "The program is configured around the client’s approved AI stack, including Microsoft 365 Copilot, Copilot Projects and Agents, Claude Skills, Plugins and approved ERP or Cloud Tally sources where available."],
  ["Does the workshop automate our full production process?", "No. The workshop creates guided prototypes and controlled workflow designs. Production automation needs stable data, integration, testing, monitoring, governance, ownership and authorization controls."],
  ["How is finance data protected?", "Activities use approved or sanitized data and keep source verification, confidentiality, access control, human review, auditability and explicit write-back authorization in place."],
  ["What do participants take back after the workshop?", "Participants receive a finance prompt library, Project and Agent blueprint, Claude Skills starter framework, reconciliation toolkit, automation playbook and a 30-day action plan."],
] as const;
const structuredData = {"@context": "https://schema.org", "@graph": [{"@type": "Course", name: "AI for Finance", description: "A customized enterprise AI program for finance productivity, reconciliation, reporting, controls and governed automation.", provider: {"@type": "Organization", name: "Ivy Professional School", url: "https://ivyproschool.com"}, teaches: ["Finance automation", "Reconciliation", "Microsoft 365 Copilot", "Finance AI agents", "Financial reporting", "AI governance"]}, {"@type": "FAQPage", mainEntity: faqs.map(([question, answer]) => ({"@type": "Question", name: question, acceptedAnswer: {"@type": "Answer", text: answer}}))}]};

export default function FinancePage() {
  return <div className={styles.page}><Navbar /><main>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html: JSON.stringify(structuredData)}} />
    <section className={styles.hero} id="top"><div className={`${styles.shell} ${styles.heroGrid}`}><div><p className={styles.eyebrow}>ENTERPRISE AI CAPABILITY PROGRAM</p><h1>AI for <span>Finance</span></h1><p className={styles.heroLead}>Turn recurring finance work into controlled, repeatable workflows. Participants use AI, Microsoft 365 Copilot and approved finance systems to improve reconciliation, reporting, exception analysis, documentation and decision support—while preserving finance review and approval.</p><div className={styles.actions}><a className={styles.button} href="#outline">Explore the program <ArrowRight size={17}/></a><a href="#customized">See how we customize</a></div><div className={styles.trust}><span><Check /> Built around approved finance data, policies and controls</span><span><Check /> Human review retained for postings and financial actions</span></div></div><aside className={styles.heroPanel}><div className={styles.panelTop}><span>FINANCE AI WORKSHOP</span><span>LIVE + HANDS-ON</span></div><div className={styles.panelCore}><p>A practical workflow journey</p>{[["01", "Prepare", "Approved source data & rules"], ["02", "Analyse", "Reconciliations, reports & exceptions"], ["03", "Control", "Review, approval & governed action"]].map(item => <div className={styles.journey} key={item[0]}><strong>{item[0]}</strong><b>{item[1]}</b><small>{item[2]}</small></div>)}<div className={styles.result}><Sparkles /><p><b>Teams leave with</b><br />Reusable prompts, finance workflow blueprints, reconciliation tools and a 30-day implementation plan.</p></div></div></aside></div></section>
    <section className={styles.proof}><div className={`${styles.shell} ${styles.proofGrid}`}>{[["8 hours", "Full-day flagship format"], ["8 modules", "From productivity to governed automation"], ["2 core labs", "Reconciliation & controlled integration"], ["12+ workflows", "Finance, treasury, tax & compliance"]].map(item => <div key={item[0]}><strong>{item[0]}</strong><span>{item[1]}</span></div>)}</div></section>
    <section className={styles.photoSection} id="program-photos"><div className={styles.photoGlow} aria-hidden="true"/><div className={styles.shell}><div className={styles.photoIntro}><div><p className={styles.eyebrow}>PREVIOUS PROGRAM HIGHLIGHTS</p><h2>Teams working on <span>real reporting and decision workflows.</span></h2></div><div className={styles.photoSummary}><p>Hands-on enterprise sessions centered on live analysis, facilitator demonstrations and team-based use-case design.</p><span>Explore the moments <ArrowRight size={15}/></span></div></div><ProgramGallery photos={programPhotos}/><p className={styles.swipeHint}>Swipe to explore <ArrowRight size={14}/></p></div></section>
    <section className={styles.section}><div className={`${styles.shell} ${styles.twoCol}`}><div><p className={styles.eyebrow}>WHY THIS PROGRAM</p><h2>Finance value grows when repetitive work becomes controlled insight.</h2></div><div className={styles.leadCopy}><p>Finance teams routinely reconcile ledgers and banks, validate tax records, prepare MIS, investigate exceptions, maintain SOPs and turn dense data into clear reporting for business leaders.</p><p>This program shows how AI can structure that work around approved sources, accounting rules, tolerances, evidence and maker-checker review—before any system action is considered.</p></div></div></section>
    <section className={styles.custom} id="customized"><div className={`${styles.shell} ${styles.customGrid}`}><p className={styles.eyebrow}>CUSTOMIZED FOR YOUR BUSINESS</p><h2>One control architecture.<br/>Your systems, policies, data and approvals.</h2><p>Before delivery, Ivy maps finance functions, approved AI tools, ERP or Cloud Tally environment, recurring reports, accounting policies, validation requirements, data-access limits and approval boundaries. Exercises are configured around actual approved or sanitized workflows and expected outputs.</p></div></section>
    <section className={styles.logoSection} id="clients" aria-labelledby="clients-heading"><div className={styles.shell}><div className={styles.logoHead}><div><p className={styles.eyebrow}>TRUSTED BY ENTERPRISE TEAMS</p><h2 id="clients-heading">Organizations we have worked with</h2></div><p>Enterprise learning experiences designed for leaders and teams across industries.</p></div></div><div className={styles.logoCarousel}><div className={styles.logoTrack}>{[...clientLogos, ...clientLogos].map((client, index) => <div className={styles.logoItem} key={`${client.name}-${index}`} aria-hidden={index >= clientLogos.length}><Image src={client.src} alt={index < clientLogos.length ? `${client.name} logo` : ""} sizes="180px"/></div>)}</div></div></section>
    <section className={styles.section}><div className={styles.shell}><div className={styles.diagnosticHead}><p className={styles.eyebrow}>CONFIGURED, NEVER OFF-THE-SHELF</p><h2>We assess the finance workflow before we design the classroom.</h2><p>Every engagement begins with participant pre-screening and an AI maturity baseline, followed by a finance process and control review. The findings determine tool depth, case complexity, source files, validation rules, demonstrations and success measures.</p></div><div className={styles.maturityBar}>{["AI & COPILOT FLUENCY", "FINANCE DATA READINESS", "CONTROL & REPORTING MATURITY", "AGENT & AUTOMATION READINESS"].map(item => <span key={item}>{item}</span>)}</div><div className={styles.diagnostic}>{[["Sponsor discovery", "Clarify finance priorities, process pain points, review cadence, system landscape and risk boundaries."], ["Participant pre-screening", "Map roles, AI and Excel comfort, current tools, recurring tasks and practical barriers."], ["Workflow baseline", "Review ledgers, statements, tax data, reports, SOPs and manual validation steps with process owners."], ["Curriculum configuration", "Select finance-relevant files, accounting rules, tolerance limits, exceptions, demonstrations and agent use cases."], ["Outcome design", "Agree learning, completion, productivity, traceability and pilot-readiness targets before delivery."]].map((item, index) => <article key={item[0]}><b>0{index + 1}</b><h3>{item[0]}</h3><p>{item[1]}</p></article>)}</div><div className={styles.configNote}><article><h3>What changes by client</h3><p>Systems, chart of accounts, source formats, tax and policy requirements, reporting cycles, tolerance rules, access model, tools and approval flow.</p></article><article><h3>What remains consistent</h3><p>Source verification, human review, confidentiality, auditability, controlled access, exception handling and clear implementation ownership.</p></article></div></div></section>
    <section className={styles.section} id="outline"><div className={styles.shell}><div className={styles.heading}><div><p className={styles.eyebrow}>FLAGSHIP OUTLINE</p><h2>Eight modules.<br/>One applied finance journey.</h2></div><p>The full-day format combines finance-specific prompting, Microsoft 365 Copilot, Copilot Projects and Agents, Claude Skills, Tally integration, reconciliation labs and implementation planning.</p></div><div className={styles.modules}>{modules.map(module => <article key={module[0]}><span>{module[0]}</span><div><h3>{module[1]}</h3><p>{module[2]}</p></div><b>{module[3]}</b></article>)}</div></div></section>
    <section className={styles.dark} id="cases"><div className={`${styles.shell} ${styles.section} ${styles.casesShell}`}><div className={styles.heading}><div><p className={styles.eyebrow}>FINANCE AUTOMATION PORTFOLIO</p><h2>Real finance processes become the learning material.</h2></div><p>Each workflow includes the business problem, required inputs, proposed automation, expected outputs and approval controls from the Finance Automation Use Case Register.</p></div><UseCaseCards cases={cases}/><div className={styles.configNote}><article><p className={styles.eyebrow}>FEATURED RECONCILIATION LAB</p><h3>From raw transactions to an audit-ready exception queue</h3><p>Participants standardize source files, apply deterministic and fuzzy matching logic, investigate exceptions and produce a concise management summary.</p><p><strong>Prepare data → Match records → Classify exceptions → Investigate → Review</strong></p></article><article><p className={styles.eyebrow}>FEATURED INTEGRATION LAB</p><h3>Controlled Cloud Tally-to-AI workflow</h3><p>Teams design a governed path from approved Tally exports or APIs to Claude Skills or Copilot analysis, keeping finance approval before any posting or write-back.</p><p><strong>Extract → Analyse → Reconcile → Finance review → Approved action</strong></p></article></div></div></section>
    <section className={styles.economics}><div className={`${styles.shell} ${styles.economicsGrid}`}><div><p className={styles.eyebrow}>FINANCE CONTROL ARCHITECTURE</p><h2>Every automation is designed for review.</h2></div><div><p className={styles.leadCopy}>Participants learn how to keep AI outputs traceable, bounded and suitable for finance use. The program begins with analysis and reconciliation before any system action is considered.</p><div className={styles.costGrid}>{[["SOURCE GROUNDING", "Use approved ledgers, statements, policies, masters and reference files."], ["VALIDATION RULES", "Specify tolerances, accounting logic, completeness checks and exception criteria."], ["MAKER-CHECKER", "Separate preparation, review and final approval responsibilities."], ["AUDIT TRAIL", "Retain matched records, exceptions, evidence and reviewer action."], ["ACCESS CONTROL", "Protect financial, vendor, customer, tax and payroll information."], ["WRITE-BACK GATE", "Require explicit authorization before draft entries, posting or system updates."]].map(item => <div key={item[0]}><strong>{item[0]}</strong><span>{item[1]}</span></div>)}</div></div></div></section>
    <section className={styles.section}><div className={styles.shell}><div className={styles.heading}><div><p className={styles.eyebrow}>HOW WE DELIVER</p><h2>Assess. Configure. Practise. Activate.</h2></div><p>The workshop connects capability building with practical finance implementation. Approved data, control ownership and measurable outcomes are designed in from the start.</p></div><div className={styles.delivery}>{delivery.map(item => <article key={item[0]}><span>{item[0]}</span><h3>{item[1]}</h3><ul>{item[2].map(point => <li key={point}>{point}</li>)}</ul></article>)}</div></div></section>
    <section className={styles.outcomes} id="outcomes"><div className={`${styles.shell} ${styles.section}`}><div className={styles.heading}><div><p className={styles.eyebrow}>OUTCOMES & IMPACT METRICS</p><h2>Measures a finance sponsor can track.</h2></div><p>Final targets should be set after baseline assessment and adjusted for process volume, data quality, system access and selected workflows.</p></div><div className={styles.metricGrid}>{metrics.map(item => <article key={item[2]}><strong>{item[0]}</strong><small>{item[1]}</small><h3>{item[2]}</h3><p>{item[3]}</p><span>{item[4]}</span></article>)}<div className={styles.note}><ShieldCheck/> These figures are proposed program targets. Actual baselines, targets and achieved results should be agreed and reported for each client engagement.</div></div></div></section>
    <section className={styles.linkedinSection} id="linkedin-posts"><div className={`${styles.shell} ${styles.section}`}><div className={styles.heading}><div><p className={styles.eyebrow}>CLIENTS MENTIONING IVY</p><h2>See the programs through our clients&apos; LinkedIn posts.</h2></div><p>Explore the professionals and client organizations connected with Ivy Professional School&apos;s leadership programs.</p></div><div className={styles.linkedinGrid}>{[{name: "Preeti N Shah", company: "Bennett Coleman & Co. Ltd.", quote: "A big thank you to Prateek Agrawal for making the sessions so fun, practical, thought-provoking & easy to connect with real-world HR challenges.", postUrl: "https://lnkd.in/p/dD-u32YW"}, {name: "Kanchan Bose", company: "MSP Steel", quote: "A big thank you to Mr. Prateek Agrawal for delivering highly practical sessions focused on real business applications of AI. It was great to explore how AI can enhance productivity, automate routine tasks, and support better decision-making.", postUrl: "https://www.linkedin.com/posts/kanchan88_%F0%9D%90%80%F0%9D%90%88-%F0%9D%90%A2%F0%9D%90%AC-%F0%9D%90%82%F0%9D%90%A1%F0%9D%90%9A%F0%9D%90%A7%F0%9D%90%A0%F0%9D%90%A2%F0%9D%90%A7%F0%9D%90%A0-%F0%9D%90%96%F0%9D%90%A8%F0%9D%90%AB%F0%9D%90%A4-%F0%9D%90%8B%F0%9D%90%9E-activity-7484436858446344192-KiVa"}, {name: "Devanganaa Sharma", company: "Bennett Coleman & Co. Ltd.", quote: "The AI for HR workshop was less about learning another tool and more about understanding what’s becoming possible. A special thanks to Prateek Agrawal for spending these two days with us and generously sharing his knowledge, perspectives and some serious AI wisdom!", postUrl: "https://lnkd.in/p/dXZZbJfb"}].map(({name, company, quote, postUrl}) => <article className={styles.linkedinSlot} key={postUrl}><h3>{name}</h3><p className={styles.clientCompany}>{company}</p><blockquote><span className={styles.quoteMark}>“</span>{quote}</blockquote><a className={styles.linkPlaceholder} href={postUrl} target="_blank" rel="noopener noreferrer" aria-label={`View ${name}'s LinkedIn post`}>VIEW LINKEDIN POST →</a></article>)}</div></div></section>
    <section className={styles.takeaways}><div className={`${styles.shell} ${styles.twoCol}`}><div><p className={styles.eyebrow}>WHAT PARTICIPANTS TAKE BACK</p><h2>A finance toolkit ready for recurring work.</h2></div><div>{takeaways.map((item, index) => <p key={item[0]}><b>{String(index + 1).padStart(2, "0")}</b><span><strong>{item[0]}</strong>{item[1]}</span></p>)}</div></div></section>
    <section className={styles.roadmap}><div className={`${styles.shell} ${styles.roadmapGrid}`}><div><p className={styles.eyebrow}>FROM WORKSHOP TO SCALE</p><h2>A phased finance journey</h2></div>{[["PHASE 1", "Quick wins", "Read-only analysis, reconciliation, prompt libraries and recurring reporting support."], ["PHASE 2", "Controlled workflows", "Projects, agents, Skills, document intake, approvals and exception routing."], ["PHASE 3", "Integrated automation", "Governed ERP or Tally connectivity, monitored performance and approved write-back."]].map(item => <article key={item[0]}><span>{item[0]}</span><h3>{item[1]}</h3><p>{item[2]}</p></article>)}</div></section>
    <section className={styles.faqSection} aria-labelledby="faq-heading"><div className={styles.shell}><div className={styles.faqHead}><p className={styles.eyebrow}>FREQUENTLY ASKED QUESTIONS</p><h2 id="faq-heading">AI for Finance, answered.</h2></div><div className={styles.faqList}>{faqs.map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></div></section>
    <section className={styles.cta}><div className={styles.shell}><p className={styles.eyebrow}>DESIGN YOUR PROGRAM</p><h2>Bring your finance priorities.<br/>We will build the learning around them.</h2><p>Share your finance functions, approved AI stack, systems, reporting cycles and priority workflows.</p><a className={styles.button} href="mailto:corporate@ivyproschool.com">Discuss your AI for Finance program <ArrowRight size={17}/></a></div></section>
  </main><Footer /></div>;
}
