import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import { ArrowRight, Check, ShieldCheck, Sparkles } from "lucide-react";
import styles from "./hr.module.css";

const useCases = [
  ["01","Quick win","HRBP Monthly Workforce Review Pack","Consolidate HRMS, payroll, attendance, hiring, attrition and L&D inputs into an evidence-led leadership pack.","HRBP / HR Analytics","2–3 months"],
  ["02","Quick win","Employee Master Data Validation","Find duplicates, missing fields and inconsistent department, grade, location, manager and cost-centre values.","HR Operations","1–2 months"],
  ["03","Quick win","Payroll Exception & Cross-Audit","Compare pay movements against attendance, leave, increments, incentives and deductions before sign-off.","Payroll / HR Ops","2–3 months"],
  ["04","Phase 1","Shift, Roster & Overtime Review","Reconcile rosters, attendance, overtime, leave and compensatory off to surface staffing and policy exceptions.","Workforce Operations","3–4 months"],
  ["05","Strategic","Manpower Cost & Budget Analytics","Decompose budget variance across units, grades and locations with drivers, forecasts and management commentary.","C&B / HR Finance","4–6 months"],
  ["06","Phase 1","Attrition & Retention Hotspots","Identify cohort concentrations while keeping patterns separate from confirmed causes and individual decisions.","HR Analytics / HRBP","3–4 months"],
  ["07","Quick win","Requirement-to-JD Workflow","Turn hiring inputs into a structured JD, role scorecard, sourcing brief and bias-aware manager checklist.","Talent Acquisition","1–2 months"],
  ["08","Quick win","Explainable CV Screening","Compare CV evidence against weighted role criteria and record information gaps without unsupported rejection.","Talent Acquisition","1–2 months"],
  ["09","Quick win","Interview Kit & Scorecard","Generate structured questions, role-specific probes, evidence guides and consistent panel evaluation formats.","TA / Interview Panel","1–2 months"],
  ["10","Phase 1","Joining Readiness Tracker","Track communications, documents, background checks, approvals and ageing risks between selection and joining.","TA / HR Operations","2–3 months"],
  ["11","Phase 1","Performance Narrative & Calibration","Improve evidence quality, flag incomplete statements and prepare rating-distribution review packs.","Performance / HRBP","3–4 months"],
  ["12","Quick win","LMS Effectiveness Review","Combine enrolment, completion, assessment and feedback data to identify cohorts and programmes needing action.","Learning & Development","2–3 months"],
  ["13","Phase 1","Employee Voice Theme Analysis","Anonymise and categorise survey and exit feedback with traceable themes, sample controls and action priorities.","Engagement / Analytics","2–3 months"],
  ["14","Strategic","HR Policy Knowledge Assistant","Answer from approved documents with citations, version control, exception routing and an unresolved-query log.","HR Ops / EX / IT","4–6 months"],
  ["15","Quick win","Engagement Communication Studio","Adapt approved HR messages across email, WhatsApp, intranet, posters and professional social channels.","Engagement / Corp Comm","1–2 months"],
];

const modules = [
  ["01","AI for HR: Focused Recap & Responsible Use","30 minutes · Common foundation",["AI, GenAI, Copilot and AI agents","Confidentiality, candidate data and payroll risk","Bias, hallucination and mandatory human review"],"Responsible AI Checklist for HR"],
  ["02","Prompt Engineering for HR","60 minutes · Hands-on",["Role, Instruction, Context and Format","Templates, filters, evaluation criteria and self-critique","Quick response versus deeper reasoning"],"HR Prompt Library: Foundation Set"],
  ["03","Microsoft 365 Copilot for HR Productivity","60 minutes · Hands-on",["Meeting transcripts to decisions, owners and deadlines","Outlook thread summaries and escalations","Word and PowerPoint management outputs"],"Meeting Minutes and Action-Tracking Template"],
  ["04","AI for Recruitment & Candidate Evaluation","75 minutes · Hands-on",["Structured JDs and role scorecards","Explainable CV comparison against explicit criteria","Interview guides, scorecards and candidate communication"],"AI-Assisted Recruitment Toolkit"],
  ["05","HR Analytics, Payroll & Operations","105 minutes · Hands-on",["HRMS and payroll validation","Attrition, salary movement and manpower cost","Dashboard cross-audit and exception reporting"],"HR Analytics and Payroll Validation Prompt Pack"],
  ["06","AI for L&D and LMS Effectiveness","30 minutes · Guided exercise",["Completion, overdue learners and assessment movement","Feedback themes and course-effectiveness review","Department-level follow-up"],"LMS Effectiveness Review Template"],
  ["07","Employee Engagement & Employer Branding","30 minutes · Guided exercise",["Multi-channel employee communication","Recognition and employer-brand stories","Tone, clarity and reputational review"],"Employee Engagement Communication Pack"],
  ["08","HR AI Implementation Roadmap","30 minutes · Group activity",["Current process, problem and input data","Workflow, risks, controls and owner","Next 30-day action and success measure"],"30-Day HR AI Action Plan"],
] as const;

const labs = [
  ["Case Lab 01 · MIS Reliability","One duplicate submission inflates reported headcount by 187.","Participants improve the prompt layer by layer, reconcile row-level arithmetic, inspect mixed formats and use remarks as evidence before producing the monthly summary.","audited executive summary + exception list + correction requests"],
  ["Case Lab 02 · Power BI","Build a workforce and manpower-cost dashboard from three Excel files.","Participants import data, create a simple model, build core DAX measures and develop KPI cards, workforce-mix charts and interactive filters.","working PBIX dashboard + validated KPI logic"],
  ["Case Lab 03 · Claude Cowork","Run a five-phase monthly HR review with a human gate at every handoff.","The workflow reconciles HR files, creates workforce and cost insights, reviews talent and learning, analyses employee voice and prepares a CHRO action pack.","CHRO review pack + action tracker + auditable workflow log"],
  ["Case Lab 04 · HR Agent Studio","Configure role-specific Copilot agents and offline HR web tools.","Teams work with agents for reporting, data quality, policy Q&A, recruitment, L&D, feedback and cross-file analysis, then prototype tools such as an onboarding tracker or interview-kit builder.","approved agent instructions + starter prompts + implementation controls"],
];

const deliverables = [
  ["HR Prompt Library","Reusable prompts for reporting, recruitment, data validation, analytics and communication."],
  ["Recruitment Toolkit","JD structure, weighted criteria, CV comparison, interview guide and evaluation scorecard."],
  ["HR Analytics Pack","Validation rules, exception reporting, manpower-cost, payroll and attrition review prompts."],
  ["Seven Copilot Agents","Ready-to-configure instructions, knowledge-source placeholders and starter prompts."],
  ["Workflow Templates","Meeting actions, LMS effectiveness, engagement communication and management reporting."],
  ["30-Day Action Plan","Prioritised workflow, owner, data requirement, controls, implementation step and measure."],
];

export default function AIForHRPage(){return <div className={styles.page}><Navbar/><main>
  <section className={styles.hero}><div className={`${styles.shell} ${styles.heroGrid}`}><div><p className={styles.eyebrow}>AI FOR HR</p><h1>Turn HR work into <span>measurable action.</span></h1><p className={styles.heroLead}>A hands-on, business-first AI programme that helps HR teams improve recruitment, employee service, workforce reporting, payroll review, learning effectiveness and people decisions through governed AI workflows.</p><div className={styles.actions}><a className={styles.button} href="#contact">Book a Programme Conversation <ArrowRight size={17}/></a><a href="#use-cases">Explore 15 HR Use Cases</a></div><div className={styles.trust}><span><Check/> Role-based learning paths</span><span><Check/> Sanitised HR case data</span><span><Check/> Human review built in</span></div></div><aside className={styles.heroPanel}><div className={styles.panelTop}><span>HR WORKFLOW STUDIO</span><span>HUMAN-CONTROLLED</span></div><div className={styles.panelCore}>{[["01","Inspect the source","HRMS, payroll, attendance, CVs, policies"],["02","Validate before analysis","Duplicates, missing fields, mismatches, bias"],["03","Create the HR output","Dashboard, shortlist, action pack, assistant"],["04","Apply the review gate","Evidence, privacy, policy and final approval"]].map(x=><div className={styles.journey} key={x[0]}><strong>{x[0]}</strong><b>{x[1]}</b><small>{x[2]}</small></div>)}<div className={styles.heroPlaceholder}><Sparkles/><p><b>Programme photograph placeholder</b><br/>Add an approved HR workshop image showing participants working with dashboards, use cases or AI agents.</p></div></div></aside></div></section>
  <section className={styles.proof}><div className={`${styles.shell} ${styles.proofGrid}`}><div><strong>18+</strong><span>years in data and AI education</span></div><div><strong>37,500+</strong><span>learners and alumni</span></div><div><strong>400+</strong><span>educators and practitioners</span></div><div><strong>300+</strong><span>corporate recruiters</span></div></div></section>
  <section className={styles.photoSection} id="program-photos"><div className={styles.photoGlow}/><div className={styles.shell}><div className={styles.photoIntro}><div><p className={styles.eyebrow}>PREVIOUS PROGRAM HIGHLIGHTS</p><h2>HR teams learning through <span>real business application.</span></h2></div><p>Reserved for approved programme photographs showing participants working with dashboards, recruitment use cases and governed AI workflows.</p></div><div className={styles.blankGallery}><div><b>01</b><span>PRIMARY PROGRAMME PHOTOGRAPH</span><small>IMAGE SPACE RESERVED</small></div><div><b>02</b><span>WORKSHOP INTERACTION</span><small>IMAGE SPACE RESERVED</small></div><div><b>03</b><span>TEAM OUTPUT</span><small>IMAGE SPACE RESERVED</small></div><div><b>04</b><span>FACILITATED CASE LAB</span><small>IMAGE SPACE RESERVED</small></div></div></div></section>
  <section className={styles.section}><div className={styles.shell}><div className={styles.heading}><div><p className={styles.eyebrow}>WHY THIS PROGRAMME</p><h2>HR has more AI opportunities than it has safe implementation paths.</h2></div><p>The programme begins with workflow evidence, data boundaries and review ownership. Tool instruction follows the business problem.</p></div><div className={styles.challengeGrid}>{[["01 / FRAGMENTED WORK","Critical HR work lives across files, emails and systems.","Monthly MIS, recruitment trackers, policies, LMS records and employee feedback require repeated consolidation before HR can act."],["02 / TRUST GAP","Fluent AI output can hide weak evidence.","Duplicates, stale regulations, inconsistent definitions and unsupported causal claims can enter management packs without deliberate checks."],["03 / ADOPTION GAP","Generic prompting rarely changes a workflow.","Teams need role-based practice, reusable templates, agents, dashboards and a 30-day implementation owner for each selected use case."]].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div><div className={styles.metrics}>{[["20–30%","Knowledge uplift target","Measured through role-relevant pre- and post-assessment."],["≥80%","Hands-on completion target","Participants finish the core case output during the programme."],["≥70%","30-day activation target","Selected teams begin using or piloting an approved HR workflow."],["15–30%","Cycle-time potential","Validated against a baseline for suitable reporting and operations tasks."]].map(x=><article key={x[1]}><strong>{x[0]}</strong><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div><p className={styles.note}><b>Measurement note:</b> These are illustrative targets for programme design. Replace them with agreed baselines and verified post-program results before publishing as client outcomes.</p></div></section>
  <section className={`${styles.section} ${styles.useCaseSection}`} id="use-cases"><div className={styles.shell}><div className={styles.heading}><div><p className={styles.eyebrow}>15 HR AI USE CASES</p><h2>Business work becomes the learning material.</h2></div><p>Each use case has a defined problem, input set, output, owner, implementation wave and human validation requirement. Eight are positioned as quick wins, five as Phase 1 priorities and two as strategic builds.</p></div><div className={styles.caseGrid}>{useCases.map(c=><article key={c[0]}><div><b>{c[0]}</b><span>{c[1]}</span></div><h3>{c[2]}</h3><p>{c[3]}</p><small>{c[4]} <i>{c[5]}</i></small></article>)}</div></div></section>
  <section className={styles.dark}><div className={`${styles.shell} ${styles.section}`}><div className={styles.heading}><div><p className={styles.eyebrow}>LEARNING ARCHITECTURE</p><h2>Progress from individual productivity to controlled agentic work.</h2></div><p>The programme mix is selected after pre-screening. Every level produces a usable output.</p></div><div className={styles.architecture}>{[["Prompt","RICF / RICTF prompts that remove ambiguity, set evidence rules and define the output."],["Copilot","Emails, meeting minutes, HR documents, presentations and management narratives."],["Dashboard","Power BI workforce and manpower-cost view with relationships, DAX and filters."],["Automation","Power Automate triggers, approvals, reminders, document handling and escalation flows."],["Agent","Seven ready-to-configure HR agents grounded in approved Microsoft 365 sources."],["Cowork","A five-phase folder workflow that creates a controlled CHRO review pack."]].map((x,i)=><article key={x[0]}><b>0{i+1}</b><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></div></section>
  <section className={styles.section} id="outline"><div className={`${styles.shell} ${styles.outline}`}><div><p className={styles.eyebrow}>PROGRAMME OUTLINE</p><h2>Practical by design. Flexible by function.</h2><p>The core eight-hour format can expand into role-based labs, implementation sprints or a multi-stage HR AI academy.</p><div className={styles.duration}><strong>8 hours</strong><span>Core programme including breaks</span></div></div><div className={styles.modules}>{modules.map((m,i)=><details open={i===0} key={m[0]}><summary><b>{m[0]}</b><span><strong>{m[1]}</strong><small>{m[2]}</small></span><i>+</i></summary><div><ul>{m[3].map(x=><li key={x}>{x}</li>)}</ul><p><b>Output</b>{m[4]}</p></div></details>)}</div></div></section>
  <section className={`${styles.section} ${styles.soft}`}><div className={styles.shell}><div className={styles.heading}><div><p className={styles.eyebrow}>CASE-BASED LEARNING</p><h2>Participants work on the kinds of files HR receives before they are clean.</h2></div><p>Cases use fictional or sanitised data. They test whether participants can validate, explain and control an AI-assisted workflow.</p></div><div className={styles.labs}>{labs.map(x=><article key={x[0]}><header><small>{x[0]}</small><h3>{x[1]}</h3></header><div><p>{x[2]}</p><b>Creates: {x[3]}</b></div></article>)}</div></div></section>
  <section className={styles.dark}><div className={`${styles.shell} ${styles.section}`}><p className={styles.eyebrow}>PARTICIPANT DELIVERABLES</p><h2>The programme ends with working assets, not attendance alone.</h2><div className={styles.delivery}>{deliverables.map((x,i)=><article key={x[0]}><b>0{i+1}</b><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></div></section>
  <section className={styles.section}><div className={styles.shell}><div className={styles.heading}><div><p className={styles.eyebrow}>BEFORE, DURING AND AFTER</p><h2>A programme shaped around your HR maturity, data and tool environment.</h2></div><p>The curriculum is modular. Participant screening decides the depth, case mix and tools used for each HR role.</p></div><div className={styles.process}>{[["Pre-screening","Role, experience, AI comfort, tool access and priority workflow survey."],["Maturity baseline","Current use, data readiness, governance controls and adoption barriers."],["Custom design","Choose use cases, datasets, licences, level tracks and success measures."],["Applied delivery","Hands-on cases, review gates, templates, agents and role-based outputs."],["Activation review","30-day pilots, adoption evidence, time baseline and implementation roadmap."]].map((x,i)=><article key={x[0]}><b>0{i+1}</b><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></div></section>
  <section className={`${styles.section} ${styles.soft}`}><div className={`${styles.shell} ${styles.economics}`}><div><p className={styles.eyebrow}>AI COST ECONOMICS</p><h2>Use deeper AI only where better reasoning changes the decision.</h2><p>The programme teaches HR teams to separate typing tasks from thinking tasks, choose the right tool boundary and quantify whether an automation deserves implementation.</p></div><div className={styles.roi}>{[["Baseline effort","Minutes × frequency × people"],["AI-assisted effort","Run time + human review"],["Quality control","Exceptions caught + rework avoided"],["Tool cost","Licence + compute + implementation"],["Adoption value","Usage × time saved × control quality"]].map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}<p><b>Business case:</b> annualised capacity value + avoided rework and risk − tool and implementation cost.</p></div></div></section>
  <section className={styles.dark}><div className={`${styles.shell} ${styles.section} ${styles.guardrails}`}><div><p className={styles.eyebrow}>RESPONSIBLE AI FOR HR</p><h2>Human judgement remains inside every sensitive decision.</h2>{["Use approved enterprise locations for employee-level data.","Show source, period, row count and calculation behind material findings.","Keep unmatched records visible; never silently delete or correct source data.","Protect anonymity and avoid reporting findings from groups that are too small.","Recruitment, appraisal, disciplinary and separation decisions stay with authorised people."].map(x=><p className={styles.guardrail} key={x}>{x}</p>)}</div><aside><ShieldCheck/><h3>Human Review Gate</h3><p>Before an output moves to leadership, HR checks unsupported claims, thin samples, ambiguous metrics, data-quality issues, sensitive inference, policy status and approval ownership.</p><p><b>Result:</b> faster work with a visible audit trail and a named decision owner.</p></aside></div></section>
  <section className={styles.cta} id="contact"><div className={styles.shell}><p className={styles.eyebrow}>BUILD YOUR HR AI PROGRAMME</p><h2>Start with the workflows your HR team needs to improve now.</h2><p>We will assess participant maturity, data readiness, tool access and business priorities, then configure the programme, case materials, deliverables and measurement plan.</p><a className={styles.button} href="mailto:corporate@ivyproschool.com?subject=AI%20for%20HR%20Programme">Book a Conversation <ArrowRight size={17}/></a></div></section>
 </main><Footer/></div>}
